### ISSUE TITLE
rocketmq-console集群页面显示问题

### ISSUE THREAD

**Issue by gouez** [apache/rocketmq-externals#108]
问题：

我有两个broker，分别是broker-a（Master），broker-b（Slave）。但是在rocketmq-console集群页面始终只会显示一个节点信息，必须刷新页面才能切换到另一个节点

![11](https://user-images.githubusercontent.com/4373882/44943886-630f9a00-ae00-11e8-946d-2395b9fbc066.png)
![22](https://user-images.githubusercontent.com/4373882/44943887-660a8a80-ae00-11e8-904f-f6610db5dfa0.png)

**Comment by drunkcz** [comment]
我碰到过这个情况，当时broker配置的namesrv地址是一个负载均衡地址，换成namesrv的list就好了。
