### ISSUE TITLE
how to consume message orderly

### ISSUE THREAD

**Issue by JamesXiao** [apache/rocketmq-externals#109]
When I set the listener to 
@RocketMQMessageListener(topic = "aaaaa", messageModel = MessageModel.BROADCASTING, consumerGroup = "bbbb", consumeMode = ConsumeMode.ORDERLY)

The consumer does not receive any message at all, 
I checked rocketmq console and can confirm that those message are successfully created from producer.

And, the consumer can consume message if I set the consumeMode to concurrently.

Could you please share some hints, what am I missing here to turn the consumer into "orderly" mode?

**Comment by JamesXiao** [comment]
It turns out that when I set the messageModle to CLUSTERING, then the consumeMode orderly works

So the question now is, why ORDERLY does not work with BROADCASTING?

**Comment by vongosling** [comment]
BROADCASTING really not support order message.

**Comment by walking98** [comment]
In above PR, I have added a check logic for this invalid usage.

**Comment by JamesXiao** [comment]
OK, thanks for the clarification
