### ISSUE TITLE
c++ asyncProducer example producer failed

### ISSUE THREAD

**Issue by lzx258** [apache/rocketmq-externals#119]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
使用rocketmq-cpp example AsyncProducer异步生产报错

```
# 同步接口正常
./bin/SyncProducer -t test-mq -g Test-Group -n 28.163.0.67:9876 -m 200
nameserver: 28.163.0.67:9876
topic: test-mq
groupname: Test-Group
produce content: msgbody for test
msg  count: 200
thread count: 8
tps: 0
tps: 0
send RT more than: 2406 ms with msgid: 1CA3004300002A9F0000002061BEA9A8
send RT more than: 2407 ms with msgid: 1CA3004300002A9F0000002061BEABB4
send RT more than: 2407 ms with msgid: 1CA3004300002A9F0000002061BEAA2B
send RT more than: 2410 ms with msgid: 1CA3004300002A9F0000002061BEACBA
send RT more than: 2410 ms with msgid: 1CA3004300002A9F0000002061BEAC37
send RT more than: 2410 ms with msgid: 1CA3004300002A9F0000002061BEAAAE
send RT more than: 2407 ms with msgid: 1CA3004300002A9F0000002061BEAB31
per msg time: 12.175ms
========================finished==============================
send RT more than: 2809 ms with msgid: 1CA3004300002A9F0000002061BF149B
tps: 210


 # 异步接口
./AsyncProducer -t test-mq -g producerGroup -n 28.163.0.67:9876 -m 200
# 报错输出
nameserver: 28.163.0.67:9876
topic: test-mq
groupname: producerGroup
produce content: msgbody for test
msg  count: 200
thread count: 8
tps: 0
tps: 0
tps: 0
tps: 0
per msg time: 20.08ms
========================finished==============================
send ExceptionType:  , msg: send msg failed due to wait response timeout or network error,error:-1,in file </rocket-cpp/src/common/AsyncCallbackWrap.cpp> line:55
```
- What did you do (The steps to reproduce)?
cd rocketmq-cpp && mkdir build && cd build && cmake .. && make 
- What did you expect to see?
producer success
- What did you see instead?
error
2. Please tell us about your environment:
         Icon name: computer-vm
           Chassis: vm
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.el7.x86_64
      Architecture: x86-64

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
none

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by lzx258** [comment]
add sleep(30)  before shutdown, asyncProducer  producer normal

**Comment by vongosling** [comment]
ping @ShannonDing @wlliqipeng

**Comment by ShannonDing** [comment]
As it is graduated  , please go here [rocketmq-client-cpp Client](https://github.com/apache/rocketmq-client-cpp).

**Comment by vongosling** [comment]
@lzx258 Community is refactoring the CPP client and willing to get it graduate from the community. Welcome to use the latest version https://github.com/apache/rocketmq-client-cpp. Any problem, please let me know.
