### ISSUE TITLE
@RocketMQMessageListener(consumeThreadMax=4,topic = "${sep.queue.meta}"

### ISSUE THREAD

**Issue by phoema** [apache/rocketmq-externals#124]
want  attr "consumeThreadMax" use value like topic ${sep.queue.meta}

**Comment by phoema** [comment]
org.apache.rocketmq.spring.starter.RocketMQAutoConfiguration
Method  registerContainer
beanBuilder.addPropertyValue(PROP_CONSUME_THREAD_MAX, environment.resolvePlaceholders(annotation.consumeThreadMax()));


org.apache.rocketmq.spring.starter.annotation.RocketMQMessageListener

**Comment by vongosling** [comment]
please check the latest code. Any problem, please let us know.
