### ISSUE TITLE
Logstash input and output plugin should be considered

### ISSUE THREAD

**Issue by LuanLouis** [apache/rocketmq-externals#135]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
      RocketMQ has supported logback extension to transfer log meesages to MQ，BUT, unforturnatly 
  There is no corresponding logstash input and output plugin to transfer my messages to ElasticSearch if I use ELK solution.

2. Provide any additional detail on your proposed use case for this feature.
    For now, I want Logstash input plugin for RocketMQ. It would be great if you guys can provide it.

**Comment by sherlock-hao** [comment]
How is it going ? Any Developer working on it ?
