### ISSUE TITLE
Rocketmq-flink can't active when be resource

### ISSUE THREAD

**Issue by Jnoson** [apache/rocketmq-externals#136]
1.when i use example with RocketMQFlinkExample，can't receive any message from mq
is the source can be active ?
2.with the rocketmq-consle web ,i can't  find the 'flink-source' consumer info

**Comment by vesense** [comment]
@Jnoson 
RocketMQFlinkExample uses `flink-source2` as the input topic. see: https://github.com/apache/rocketmq-externals/blob/master/rocketmq-flink/src/test/java/org/apache/rocketmq/flink/example/RocketMQFlinkExample.java#L45
So, Writing data to it before you run RocketMQFlinkExample.
