### ISSUE TITLE
cannot throw exception which means message willbe always commited and no resending

### ISSUE THREAD

**Issue by jonesmith518** [apache/rocketmq-externals#137]
https://github.com/apache/rocketmq-externals/blob/ddeb5f19ef3a9b88d6a89d10008a35f2fde61544/rocketmq-spring-boot-starter/src/main/java/org/apache/rocketmq/spring/starter/core/RocketMQListener.java#L21

**Comment by flyilxm** [comment]
throw the RuntimeException？

**Comment by vongosling** [comment]
@walking98

**Comment by walking98** [comment]
@jonesmith518 @flyilxm 
It is acceptable to throw RuntimeException is this case, the up layer will catch it and mark consumer status as RECONSUME_LATER.
