### ISSUE TITLE
the rocketmq.version which is in the rocketmq-console project's pom file is too old

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq-externals#147]
1.What is the purpose of the change?

When I develop the message track trace feature,I found the the rocketmq.version which is in the rocketmq-console project's pom file and master branch is too old.The rocketmq.version tag in the pom file is 4.0.0.But I will change some codes in the rocketmq common project.

2.Optimization change action
So I will change rocketmq.version tag which is in the pom file of master branch and  rocketmq-console project to 4.4.0-SNAPSHOT.

**Comment by zongtanghu** [comment]
`<properties>
      ......  
      <rocketmq.version>4.4.0-SNAPSHOT</rocketmq.version>
      ......
    </properties>`

**Comment by vongosling** [comment]
@zongtanghu Cool.

**Comment by vongosling** [comment]
@zongtanghu Let's work on your latest pr for console
