### ISSUE TITLE
Caused by: org.apache.rocketmq.client.exception.MQClientException: No route info of this topic, 

### ISSUE THREAD

**Issue by xuezhongyu01** [apache/rocketmq-externals#150]
how can I create a rocketmq broker container in docker ,which can with parameter autocreatetopic?

**Comment by vongosling** [comment]
@xuezhongyu01 Please read the RocketMQ Docker ReadME.

**Comment by xuezhongyu01** [comment]
我是问rockermq broker容器启动，怎么设置自动创建topic,你readme里没写
