### ISSUE TITLE
go client 可使用的功能有哪些呢？

### ISSUE THREAD

**Issue by lzzjingcairensheng** [apache/rocketmq-externals#155]
直接运行example 都有问题。
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/apache/incubator-rocketmq-externals/rocketmq-go/util.GetIp4Bytes(0xc0000afb08, 0xc00014e420, 0xc000000300)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/util/ip.go:28 +0x6d
github.com/apache/incubator-rocketmq-externals/rocketmq-go/model/message.generatorMessageClientIdPrefix(0x741398, 0x5d5178)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/model/message/message_client_id_generator.go:80 +0x34
github.com/apache/incubator-rocketmq-externals/rocketmq-go/model/message.generatorMessageClientId(0x0, 0x0)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/model/message/message_client_id_generator.go:50 +0x33c
github.com/apache/incubator-rocketmq-externals/rocketmq-go/model/message.(*MessageImpl).GeneratorMsgUniqueKey(0xc0000765c0)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/model/message/message_impl.go:135 +0x74
github.com/apache/incubator-rocketmq-externals/rocketmq-go/kernel.(*DefaultProducerService).doSendMessage(0xc0000f68a0, 0xc0000765c0, 0x5ca3bd, 0x4, 0xc000164040, 0x1b, 0x1, 0x5ca33d, 0x4, 0x0, ...)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/kernel/producer_service.go:217 +0x1ae
github.com/apache/incubator-rocketmq-externals/rocketmq-go/kernel.(*DefaultProducerService).sendMsgUseTopicPublishInfo(0xc0000f68a0, 0xc0000765c0, 0x5ca33d, 0x4, 0x0, 0x0, 0xc00014e240, 0xbb8, 0x0, 0x5ad5e0, ...)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/kernel/producer_service.go:189 +0x1be
github.com/apache/incubator-rocketmq-externals/rocketmq-go/kernel.(*DefaultProducerService).sendDefaultImpl(0xc0000f68a0, 0xc0000765c0, 0x5ca33d, 0x4, 0x0, 0x0, 0xbb8, 0x5be0c0, 0x0, 0x5f7480)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/kernel/producer_service.go:78 +0x25d
github.com/apache/incubator-rocketmq-externals/rocketmq-go/kernel.(*DefaultMQProducer).Send(0xc0000f6870, 0x5f7480, 0xc0000765c0, 0x5f7480, 0xc0000765c0, 0x10)
	/home/lzz/go/pkg/mod/github.com/apache/incubator-rocketmq-externals@v0.0.0-20180805031651-550595376d55/rocketmq-go/kernel/mq_producer.go:47 +0x7c
main.main()
	/home/lzz/go/src/gitlab.bytestar.io/grpc/grpcapi/example/simple_producer.go:45 +0x2d4

**Comment by ShannonDing** [comment]
Which Go SDK do you use now? for more information , Please move tp [rocketmq-client-go](https://github.com/apache/rocketmq-client-go)
