### ISSUE TITLE
How to create the topic automatically in docker

### ISSUE THREAD

**Issue by xuezhongyu01** [apache/rocketmq-externals#158]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by huanwei** [comment]
@xuezhongyu01 What do you mean automatically creating topic after broker starts?

**Comment by vongosling** [comment]
@xuezhongyu01 ping

**Comment by xuezhongyu01** [comment]
> @xuezhongyu01 What do you mean automatically creating topic after broker starts?

i mean now i start the broker container by  command "docker start rocketmq-broker" , but I want set up the broker container start with automatically creating topic ,do u know the command how can I run broker container which can  automatically creating topic,maybe like "docker --xxx start rocketmq-broker"?

**Comment by xuezhongyu01** [comment]
> @xuezhongyu01 ping

pong~

**Comment by huanwei** [comment]
@xuezhongyu01 Actually there is default cluster and some default topics created:

```
[root@k8s-master ~]# kubectl exec -it rocketmq-5b6f6d4944-m8qhs bash
Defaulting container name to broker.
Use 'kubectl describe pod/rocketmq-5b6f6d4944-m8qhs -n default' to see all of the containers in this pod.
[root@rocketmq-5b6f6d4944-m8qhs rocketmq-4.2.0]# cd bin
[root@rocketmq-5b6f6d4944-m8qhs bin]# pwd
/opt/rocketmq-4.2.0/bin
[root@rocketmq-5b6f6d4944-m8qhs bin]# ./mqadmin clusterList -n 127.0.0.1:9876
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
#Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
DefaultCluster    rocketmq-5b6f6d4944-m8qhs  0     192.168.196.31:10911   V4_2_0_SNAPSHOT          0.00(0,0ms)         0.00(0,0ms)          0 428701.87 -1.0000
[root@rocketmq-5b6f6d4944-m8qhs bin]#     
[root@rocketmq-5b6f6d4944-m8qhs bin]# ./mqadmin topicList -n 127.0.0.1:9876
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
rocketmq-5b6f6d4944-m8qhs
BenchmarkTest
OFFSET_MOVED_EVENT
TBW102
SELF_TEST_TOPIC
DefaultCluster
[root@rocketmq-5b6f6d4944-m8qhs bin]# 
```

**Comment by xuezhongyu01** [comment]
> @xuezhongyu01 Actually there is default cluster and some default topics created:
> 
> ```
> [root@k8s-master ~]# kubectl exec -it rocketmq-5b6f6d4944-m8qhs bash
> Defaulting container name to broker.
> Use 'kubectl describe pod/rocketmq-5b6f6d4944-m8qhs -n default' to see all of the containers in this pod.
> [root@rocketmq-5b6f6d4944-m8qhs rocketmq-4.2.0]# cd bin
> [root@rocketmq-5b6f6d4944-m8qhs bin]# pwd
> /opt/rocketmq-4.2.0/bin
> [root@rocketmq-5b6f6d4944-m8qhs bin]# ./mqadmin clusterList -n 127.0.0.1:9876
> OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
> #Cluster Name     #Broker Name            #BID  #Addr                  #Version                #InTPS(LOAD)       #OutTPS(LOAD) #PCWait(ms) #Hour #SPACE
> DefaultCluster    rocketmq-5b6f6d4944-m8qhs  0     192.168.196.31:10911   V4_2_0_SNAPSHOT          0.00(0,0ms)         0.00(0,0ms)          0 428701.87 -1.0000
> [root@rocketmq-5b6f6d4944-m8qhs bin]#     
> [root@rocketmq-5b6f6d4944-m8qhs bin]# ./mqadmin topicList -n 127.0.0.1:9876
> OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=128m; support was removed in 8.0
> rocketmq-5b6f6d4944-m8qhs
> BenchmarkTest
> OFFSET_MOVED_EVENT
> TBW102
> SELF_TEST_TOPIC
> DefaultCluster
> [root@rocketmq-5b6f6d4944-m8qhs bin]# 
> ```

thank u told me what I had know thing,but I don't know it's how to set up or change broker container make it  allow producer create topic automatically

**Comment by huanwei** [comment]
@xuezhongyu01 Once you set up the RocketMQ containers, you can write your producer client to connect with broker and create whatever topics you want.
