### ISSUE TITLE
你好 ，rocketmq重启后rocketmq-console 集群生产和消费总数显示为0

### ISSUE THREAD

**Issue by zhangxuebao** [apache/rocketmq-externals#159]
您好，用的是rocketmq4.3 重启后发现rocketmq-console web 控制台，在集群显示生产总数和消费总数为零，详细如下图，麻烦您了。
https://www.zxblinux.com/phpmyadmin/rocekmq.png

**Comment by vongosling** [comment]
请把你的详细信息发到user邮件列表里，你提供的信息太模糊了
