### ISSUE TITLE
控制台创建Topic问题

### ISSUE THREAD

**Issue by davidpdw** [apache/rocketmq-externals#162]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

    在控制台上创建Topic时，只选择一个Broker

![default](https://user-images.githubusercontent.com/15335431/48933193-5fd90580-ef3a-11e8-92f6-6dbdfebb4f57.png)
- What did you expect to see?

    只在一个broker上面创建Topic
- What did you see instead?

    所有的Broker都创建了Topic
![default](https://user-images.githubusercontent.com/15335431/48933250-94e55800-ef3a-11e8-8336-b112cc3466e4.png)

2. Please tell us about your environment:

    控制台master分支

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by walking98** [comment]
broker1和broker2是什么关系？ 主从吗？@davidpdw

**Comment by davidpdw** [comment]
好的，下次用英文描述.
我发现这个问题是什么原因造成的了，我查看代码发现他是取的 cluster 下所有 broker 和页面上填写的broker 做的合集，而我理解页面功能是填写对应 cluster 下哪个 broker 需要创建topic，这个应该不是bug

**Comment by walking98** [comment]
嗯，我用最新的console方式，没有重现这个问题：
我的环境是这样的:
1. console 本机启动 :  mvn -Drocketmq.namesrv.addr=localhost:9876 spring-boot:run
2. nameserver 本机启动：  ./mqnamesrv -n 0.0.0.0:9876
3. broker-a 本机启动:  ./bin/mqbroker -n localhost:9876 -c conf/2m-noslave/broker-a.properties 
4. broker-a 远程启动:  ./bin/mqbroker -n XXXX:9876 -c conf/2m-noslave/broker-b.properties 

创建topic的时候会控制台日志出现这条记录:
INFO op=look topicCreateOrUpdateRequest={"clusterNameList":["DefaultCluster"],"brokerNameList":["broker-a"],"topicName":"WISEKING_A","writeQueueNums":16,"readQueueNums":16,"perm":6,"order":false}

这里显示的brokerNameList没有问题， console页面上看到也没有问题。

**Comment by walking98** [comment]
如果你觉得没有问题，可以把这个ISSUE先关掉吧 @davidpdw
