### ISSUE TITLE
 Who's using RocketMQ

### ISSUE THREAD

**Issue by wlliqipeng** [apache/rocketmq-externals#163]
## Who is Using  RocketMQ
First of all, thanks sincerely for constantly using and supporting RocketMQ. We will try our best to keep RocketMQ better, and keep growing community and eco-system.
## The purpose of this issue
* We’d like to listen to the community to make RocketMQ better.
* We want to attract more people to contribute to RocketMQ.
* We're willing to learn more RocketMQ use scenarios in the field for better planning.
## What we expect from you
Pls. submit a comment in this issue to include the following infomation:
* your company, school or organization.
* your city and country.
* your contact info: blog, email, twitter (at least one).
* for what business scenario do you use RocketMQ
* You can refer to the following sample answer for the format
```
 Orgnizatioin: Alibaba
 Location: Hangzhou, China
 Contact: ian.luo@gmail.com
 Purpose: used as cornerstone in distributed service architecture alibaba switched years ago.
```
Thanks again for your participation !
RocketMQ  Team

## 谁在使用RocketMQ
首先诚挚地感谢每一位持续关注并使用RocketMQ的朋友。我们会持续投入，把 RocketMQ 变得更好，把 RocketMQ 社区和生态变得更加繁荣.

## 此 Issue 的目的
* 聆听社区的声音，让 RocketMQ 变得更好
* 吸引更多的人参与贡献
* 更多的了解 RocketMQ 的实际使用场景，以方便下一步的规划

## 我们期待您能提供
在此提交一条评论, 评论内容包括:
* 您所在公司、学校或组织
* 您所在的城市、国家
* 您的联系方式: 微博、邮箱、微信 (至少一个)
* 您将 RocketMQ 用于哪些业务场景
* 您可以参考下面的样例来提供您的信息：
```
* 组织：阿里巴巴
* 地点：中国杭州
* 联系方式：ian.luo@gmail.com
* 场景：阿里内部服务化改造
```
再次感谢您的参与
RocketMQ团队

**Comment by smthing** [comment]
* 地点：中国杭州
* 联系方式：zhengjunweimail@163.com
* 场景：本人是某AIO通信框架的作者，原本想尝试将rocketmq的通信模块替换成自己的项目，却发现mq重度耦合了netty，而且这种耦合从remoting模块延伸到其他模块汇中。请问未来能否将通信组件设计成可替换的，或者降低耦合性，将这种依赖控制在较小的范围内也行。

**Comment by vongosling** [comment]
@smthing 感谢你关注RocketMQ社区，请问你的框架仓库可发出来看看，RocketMQ 依赖netty，在5.0版本会抽象，默认实现还是会使用netty，但是你也可以替换成grizzly等类似框架。另外，请仔细阅读issue模板内容，你的一言一行代表中国，不要把之前的issue内容复制到这里来，感谢你的理解。

**Comment by smthing** [comment]
@vongosling 你好，我是按照你们的模板提的issue，请问有何不妥之处。另外，我仅仅是反馈了个人在mq改造中遇到的一些困惑而选择与你们交流一下，为什么会上升到国家层面，开源跟政治也是挂钩的吗？

**Comment by super-organism** [comment]
先把文档建立起来吧 这么大的应用 只支持加java GO、python 都没个说明  哪个是最新的都搞不清楚，乱七八糟的
