### ISSUE TITLE
Send delay message in RocketMQTemplate directly

### ISSUE THREAD

**Issue by techzealot** [apache/rocketmq-externals#167]
**FEATURE REQUEST**

1. send delay message in RocketMQTemplate

2. now we can't send delay message in RocketMQTemplate directly ,we have to get the inner DefaultMQProducer to do that.

**Comment by walking98** [comment]
we will look at this feature and improve it in spring-boot.

**Comment by zyw** [comment]
This function is urgently needed. :1234:

**Comment by walking98** [comment]
Hi guys, we will add this func soon.

would you please work around it in the locally if needed?

public SendResult syncSend(String destination, Message<?> message, long timeout)  == >
public SendResult syncSend(String destination, Message<?> message, long timeout, int delayLevel) 
    
org.apache.rocketmq.common.message.Message rocketMsg = ...

rocketMsg.setDelayTimeLevel(delayLevel);

@zyw

**Comment by zyw** [comment]
OK,thanks

**Comment by vongosling** [comment]
@zyw The latest version has supported the schedule message. please feel free to use it.
