### ISSUE TITLE
Why the last message was not consumed in the rocketmq-spark

### ISSUE THREAD

**Issue by wssnail** [apache/rocketmq-externals#168]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT?** 

 1.Please describe the issue you observed

- what did you do?
RocketMQ is running, and i run the Spark Streaming , everything is ok. But the last message is printed and it dosen't seem to be consumed.
I try to restart the Spark Streaming,the last message was consumed repeatedly.  
I want to know how to modify it.
![delay](https://user-images.githubusercontent.com/6237069/49233457-063c7380-f431-11e8-8b1b-75702b26356a.png)

2.Please tell us about your environment:
I use the latest Source to compiler or use the Binary both, the errors are the same.

I tried the official example and it worked.
`sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer`
`sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer`

**Comment by Suhuang** [comment]
I got the same question.Do you have any solution?

**Comment by Suhuang** [comment]
> The issue tracker is **ONLY** used for bug report and feature request.
> 
> Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).
> 
> **BUG REPORT?**
> 
> 1.Please describe the issue you observed
> 
> * what did you do?
>   RocketMQ is running, and i run the Spark Streaming , everything is ok. But the last message is printed and it dosen't seem to be consumed.
>   I try to restart the Spark Streaming,the last message was consumed repeatedly.
>   I want to know how to modify it.
>   ![delay](https://user-images.githubusercontent.com/6237069/49233457-063c7380-f431-11e8-8b1b-75702b26356a.png)
> 
> 2.Please tell us about your environment:
> I use the latest Source to compiler or use the Binary both, the errors are the same.
> 
> I tried the official example and it worked.
> `sh bin/tools.sh org.apache.rocketmq.example.quickstart.Producer`
> `sh bin/tools.sh org.apache.rocketmq.example.quickstart.Consumer`

Hey wssnai，
I get the way to solve it. The commit offset should be untiloffset instead of untiloffset-1.
  protected def commitAll(): Unit = {
    val m = new ju.HashMap[MessageQueue, jl.Long]
    var osr = commitQueue.poll()
    try {
      while (null != osr) {
        //Exclusive ending offset
        val mq = new MessageQueue(osr.topic, osr.brokerName, osr.queueId)
        //kc.updateConsumeOffset(mq, osr.untilOffset - 1)
        //m.put(mq, osr.untilOffset - 1)

       //modify
        kc.updateConsumeOffset(mq, osr.untilOffset)
        m.put(mq, osr.untilOffset)

        osr = commitQueue.poll()
      }
      if (commitCallback.get != null) {
        commitCallback.get.onComplete(m, null)
      }
    } catch {
      case e: Exception => {
        if (commitCallback.get != null)
          commitCallback.get.onComplete(m, e)
      }
    }
  }
