### ISSUE TITLE
在rocketmq-console-ng无法查询消息明细

### ISSUE THREAD

**Issue by mingtian110** [apache/rocketmq-externals#176]
3.2版本的rocketmq的msgid生成是依据broker的ip生成的,4.x的生成是依据消费端的ip,
查看org.apache.rocketmq.common.message.MessageDecoder这个工具类里有两个方法:org.apache.rocketmq.common.message.MessageDecoder#decodeMessageId和org.apache.rocketmq.common.message.MessageDecoder#createMessageId(java.net.SocketAddress, long)
根据msgid解密的时候有用decodeMessageId,但是createMessageId却没有调用的地方,现在msgid的生成好像是在org.apache.rocketmq.common.message.MessageClientIDSetter这个里面.
现在在rocketmq-console-ng查询3.2版本的消息明细是正常的,
现在根据msgid查询4.x版本的消息明细查不了了,请问有什么解决方法吗?

**Comment by mingtian110** [comment]
感觉msgid的生成和解密没使用互相对应的方法导致console-ng上的4.x的消息无法查到,有办法可以处理掉吗?

**Comment by mingtian110** [comment]
现在我们使用上:mq的broker端是3.2版本,但是生产者客户端是用的4.x版本.

**Comment by ymwneu** [comment]
在4.X版本中，有两个message id的概念，一个是producer端生成的message id，另一个是broker端生成的message id（称为offset message id）。Producer发送消息时，由producer调用MessageClientIDSetter生成message id，后面左右unique key使用。broker端接收到消息后，会生成offset message id，这个id的生成规则是store host+物理offset，MessageDecoder类里处理的是offset message id。
在3.X版本中，只有offset message id。
3.x和4.x的message id不兼容，还是建议你升级broker客户端到4.x版本。

**Comment by vongosling** [comment]
@mingtian110 感谢你关注RocketMQ，请注意issue目前不提供问题支持，具体请参考issue模板。如果你有其它使用上的问题，请订阅user邮件列表并发送你的问题到这里，地址:http://rocketmq.apache.org/about/contact/。感谢你的配合与支持。

**Comment by mingtian110** [comment]
> 在4.X版本中，有两个message id的概念，一个是producer端生成的message id，另一个是broker端生成的message id（称为offset message id）。Producer发送消息时，由producer调用MessageClientIDSetter生成message id，后面作为unique key使用。broker端接收到消息后，会生成offset message id，这个id的生成规则是store host+物理offset，MessageDecoder类里处理的是offset message id。
> 在3.X版本中，只有offset message id。
> 3.x和4.x的message id不兼容，还是建议你升级broker端到4.x版本。

好的  谢谢

**Comment by mingtian110** [comment]
> @mingtian110 感谢你关注RocketMQ，请注意issue目前不提供问题支持，具体请参考issue模板。如果你有其它使用上的问题，请订阅user邮件列表并发送你的问题到这里，邮件列表地址请参考[这里](http://rocketmq.apache.org/about/contact/)。感谢你的配合与支持。

好的 谢谢
