### ISSUE TITLE
maven check and test err

### ISSUE THREAD

**Issue by super-organism** [apache/rocketmq-externals#180]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**
![image](https://user-images.githubusercontent.com/29723072/49577127-b8b88d00-f981-11e8-84cb-9956e93b56b4.png)

![image](https://user-images.githubusercontent.com/29723072/49577097-a50d2680-f981-11e8-8444-a39982712118.png)
---------------------------------------------------------------
![image](https://user-images.githubusercontent.com/29723072/49577217-e7cefe80-f981-11e8-8f54-2d911015761b.png)

![image](https://user-images.githubusercontent.com/29723072/49577205-e1d91d80-f981-11e8-902e-7e06d8aa8a73.png)

2. Please tell us about your environment:
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by walking98** [comment]
The test case run ok for me. Just need to make sure:
1. The test case will startup NameServer & Broker at init phase, so don't startup RMQ outside the test case. or comment out the line startMQ()  in the unit test case setUp() method. 
2. The rows have been replicated into MQ topic before consuming them out. 
    a. According to your network situation, set sendMessageTimeout with fit value in org.apache.rocketmq.hbase.sink.RocketMQProducer, e.g.  producer.setSendMsgTimeout(30000);
    b. Sleep more time in ReplicatorTest to wait replica done. line // wait for data to be replicated
