### ISSUE TITLE
关于rocketmq-spark怎么消费阿里云上的消息队列问题

### ISSUE THREAD

**Issue by bingzhan0613** [apache/rocketmq-externals#182]
公司买的阿里云消息队列MQ, 怎么用rocketmq-spark去阿里云的消息队列中消费数据呀，用ONSFactory写的client，没有问题，但是用rocketmq-spark，就不知道该怎么去消费阿里云消息队列了

**Comment by vongosling** [comment]
阿里云消息队列需要鉴权体系，目前这块还不支持。另外需要说明的是，下次请仔细阅读issue模板，咨询问题请发邮件到user邮件列表里，那里响应会更及时，http://rocketmq.apache.org/about/contact/
