### ISSUE TITLE
How to configure brokerIP1 in docker

### ISSUE THREAD

**Issue by giraffe-tree** [apache/rocketmq-externals#185]
This is the first time I use RocketMQ.
So I use the script `https://github.com/apache/rocketmq-externals/blob/master/rocketmq-docker/4.3.0/play-docker.sh`  and it run correctly. 
But when I want to configure it , I met some problems.

```sh
chen:4.3.0# docker exec -it rmqbroker /bin/bash
[root@b7501a790d74 rocketmq-4.3.0]# bin/mqbroker -m
2018-12-14 19\:28\:46 INFO main - namesrvAddr=xxx.xxx..xxx.xxx:9876
2018-12-14 19\:28\:46 INFO main - brokerIP1=172.17.0.5
2018-12-14 19\:28\:46 INFO main - brokerName=b7501a790d74
2018-12-14 19\:28\:46 INFO main - brokerClusterName=DefaultCluster
2018-12-14 19\:28\:46 INFO main - brokerId=0
2018-12-14 19\:28\:46 INFO main - autoCreateTopicEnable=true
....
```

IP  `172.17.0.5` is the private IP in docker. 
But I want to change it .
So I configured the file

```sh
## add brokerIP1=xx.xx.xx.xx
vi conf/broker.conf

## then return and restart 
docker restart rmqbroker
```

But the file `conf/broker.conf` didn't  take effect. 

```
## this is docker log 
The broker[b7501a790d74, 172.17.0.5:10911] boot success. serializeType=JSON and name server is xx.xx.xx.xx:9876
```

and the no changed config 

```
[root@b7501a790d74 rocketmq-4.3.0]# bin/mqbroker -m
2018-12-14 19\:28\:46 INFO main - namesrvAddr=xx.xx.xx.xx:9876
2018-12-14 19\:28\:46 INFO main - brokerIP1=172.17.0.5
2018-12-14 19\:28\:46 INFO main - brokerName=b7501a790d74
2018-12-14 19\:28\:46 INFO main - brokerClusterName=DefaultCluster
2018-12-14 19\:28\:46 INFO main - brokerId=0
....
```

**How to configure it ?**

**Comment by PrinsWu** [comment]
@giraffe-tree 
Hi, I have the same issue and I have fixed it.
You can reference the document as bellow
https://medium.com/@prinswu/rocketmq-with-docker-compose-%E7%9C%9F%E7%9A%84%E5%BE%88%E5%A4%9A%E5%9D%91-d1bd41e26090

**Comment by huanwei** [comment]
@giraffe-tree @PrinsWu And if you want to use customized configuration for broker.conf, you can achieve this way introduced in README. [https://github.com/apache/rocketmq-externals/blob/master/rocketmq-docker/README.md#frequently-asked-questions
](url).

Anyway, if you still have problems with RocketMQ Docker, please let me know. I will give help.

**Comment by PrinsWu** [comment]
> @giraffe-tree @PrinsWu And if you want to use customized configuration for broker.conf, you can achieve this way introduced in README. [https://github.com/apache/rocketmq-externals/blob/master/rocketmq-docker/README.md#frequently-asked-questions ](url).
> 
> Anyway, if you still have problems with RocketMQ Docker, please let me know. I will give help.

HI huanwei,
Yes, I need your help.

**Comment by Jnoee** [comment]
我也遇到这个问题，用的是docker swarm集群。namesrv识别出来的broker是集群内部IP地址，集群外调用时就会报错。创建容器时不能通过命令配置brokerIP1项。有什么好解决方案？

**Comment by vongosling** [comment]
This problem has been solved. Please use the latest code to check it.
