### ISSUE TITLE
console Caused by: org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <null> failed

### ISSUE THREAD

**Issue by yunnian** [apache/rocketmq-externals#186]
docker 启动时报错 ，如题

**Comment by tryIdea** [comment]
改成实际的ip `docker run --name rmqconsole -e "JAVA_OPTS=-Drocketmq.namesrv.addr=192.168.3.115:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false" -p 8080:8080 -t styletang/rocketmq-console-ng`

**Comment by tryIdea** [comment]
改成实际的ip
`docker run --name rmqconsole -e "JAVA_OPTS=-Drocketmq.namesrv.addr=192.168.3.115:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false" -p 8080:8080 -t styletang/rocketmq-console-ng`

**Comment by yunnian** [comment]
@tryIdea 多谢 已经解决了 主要还是没有写对宿主机的ip
