### ISSUE TITLE
Create topic on the console

### ISSUE THREAD

**Issue by zhangjidi2016** [apache/rocketmq-externals#191]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
When creating a topic on the console, only one broker is selected
![image](https://user-images.githubusercontent.com/18254437/50679171-48af2c80-103d-11e9-87ec-6aabc3a47428.png)

- What did you expect to see?
Only the topic is created on the selected broker

- What did you see instead?
All the broker in the cluster created this topic

2. Please tell us about your environment:
A namesrv and two master broker in the cluster
 
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by walking98** [comment]
The current behavior is you can select other brokers in the cluster in the BrokerName dropdown list.
