### ISSUE TITLE
rocketmq-console 最新提交的 pom 中一些依赖无法下载

### ISSUE THREAD

**Issue by RockeyCui** [apache/rocketmq-externals#196]
rocketmq-console 最新提交的 pom 中一些依赖无法下载，如图
![image](https://user-images.githubusercontent.com/22736406/50757186-7d1f2480-1299-11e9-85ba-09112fca0eff.png)

**Comment by machihaoyu** [comment]
修改rocketmq的版本号就可以了，在pom文件中修改

**Comment by hzm-January** [comment]
修改rocketmq的版本号为4.3.2不行，代码中有一些依赖
![image](https://user-images.githubusercontent.com/37241024/50838715-a626de80-1399-11e9-91b1-3af5d818b1df.png)

**Comment by artz001** [comment]
我也是这个问题,4.4.0的快照版本没有 他们阿里的库里也没有

**Comment by mcgithu** [comment]
对啊 我也是这个问题  但是不知道怎么解决，怎么办？？？

**Comment by guobingxu** [comment]
希望尽快解决一下哈！急用。

**Comment by a252937166** [comment]
我拉取了rocketmq `4.4.0-SNAPSHOT` 版本，本地install之后还是找不到`org.apache.rocketmq.client.trace`这个包

**Comment by mxz668** [comment]
依赖的jar不能下载啊

**Comment by mxz668** [comment]
有没有下载4.3的方式，这个没法用

**Comment by xuhua912** [comment]
download source code, then revert the code to pervious version

**Comment by vongosling** [comment]
大家暂别着急，4.4版本近期会发布，会解决这个问题。因为这个版本引入了tracing机制，目前代码在develop分支，可以clone这个分支，然后本地install临时解决。
