### ISSUE TITLE
About the exact-once source provided by rocketmq-flink

### ISSUE THREAD

**Issue by clay4444** [apache/rocketmq-externals#201]
In rocketmq-flink, I have some questions about rocketmqsource. Suppose two cases, 

assuming that 1.context.collectWithTimestamp(data, msg.getBornTimestamp()); sends data, only a part is sent at this time, and all of them have not been sent successfully. There is a problem with the program. At this point, assume that the snapshotState method has been executed, but the unionOffsetStates still stores the offset before reading all the messages. At this time, restart, the offset in unionOffsetStates is all imported into restoredOffsets, and then continue to execute the run method. , getMessageQueueOffset gets the offset, offsetTable certainly does not, then it will be obtained from the restoredOffsets, at this time, there is repeated consumption. 

Assume 2, this batch of data has been sent, but the snapshotState method failed to execute. At this time, although the data is sent, the offset of the last offsetTable read data is not saved. At this time, restart, this will be The batch and the previous batch of data are re-consumed once and then re-read, thus producing more serious repetitive consumption;

**Comment by vongosling** [comment]
@vesense ping

**Comment by duhanmin** [comment]
而且switch中自定义配置并不会启用，完全是鸡肋代码

**Comment by SuXingLee** [comment]
@clay4444 you opinion is right. rocketmq-flink don't keep exactly once semantic .
But nowtime by  [update consumer offset after checkpoint completed](https://github.com/apache/rocketmq-externals/pull/229) this PR  had been fix this problem.
this PR cache offset first , and store/commit  offset after checkpoint excute  successfully.
