### ISSUE TITLE
How to enable LOGIN function for user permission controlling in RocketMQ-console ?

### ISSUE THREAD

**Issue by icersummer** [apache/rocketmq-externals#205]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
For now , the console if running well, but the console-homepage has no-login-require to anybody. For the production environment, it's not safe for rockectmq data. 

2. Provide any additional detail on your proposed use case for this feature.
I'm thinking we can have a property controlling enable login-function or not. If login-function is enabled, everyone who wants to acces the roqcketmq console, should get grants by administrator.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have.
No workarounds for now.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by inotgaoshou** [comment]
agree that.

**Comment by walking98** [comment]
I will work on this, to provide this kind of function. #247
