### ISSUE TITLE
When will the mqtt plug-in be released

### ISSUE THREAD

**Issue by Quiter2013** [apache/rocketmq-externals#206]
When will the mqtt plug-in be released？
Looking at the source code, I feel that there are still many things left unrealized.

![image](https://user-images.githubusercontent.com/4453124/51951584-31166880-2470-11e9-8449-bef8ffb84b53.png)

**Comment by Quiter2013** [comment]
When will the mqtt plug-in be released

**Comment by walking98** [comment]
This issue seems duplicated with #218, there is a mqtt branch in  main project.
