### ISSUE TITLE
Rocketmq-console 报错，CODE: 17 DESC: No topic route info in name server for the topic: %RETRY%FILTERSRV_CONSUMER.

### ISSUE THREAD

**Issue by makeaaron** [apache/rocketmq-externals#207]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by AarynArwin** [comment]
你这个报错应该不是这个console组件引起的，而是你启动broker的时候需要添加启动参数，具体参考博文https://blog.csdn.net/jiangyu1013/article/details/81478754

**Comment by chenk008** [comment]
> 你这个报错应该不是这个console组件引起的，而是你启动broker的时候需要添加启动参数，具体参考博文https://blog.csdn.net/jiangyu1013/article/details/81478754

启动了autoCreateTopicEnable 还是报错，不是这个问题引起。是%RETRY%这个的问题

**Comment by worldcoding** [comment]
> > 你这个报错应该不是这个console组件引起的，而是你启动broker的时候需要添加启动参数，具体参考博文https://blog.csdn.net/jiangyu1013/article/details/81478754
> 
> 启动了autoCreateTopicEnable 还是报错，不是这个问题引起。是%RETRY%这个的问题

你好，这个问题我也遇到了，请问你是怎么解决？求指教

**Comment by wc599939522** [comment]
你好，这个问题我也遇到了，请问你是怎么解决？求指教

**Comment by cimastone** [comment]
今天我也遇到了这个问题
服务器上跑的版本上4.7.0，本地跑的client是4.3.0；跟踪源码得；生产者在与namesrv连接时，会从namesrv获取topic对应的broker信息，当没有该topic时，会以AUTO_CREATE_TOPIC_KEY默认key去获取broker信息，然后连接broker；broker再进行判断是否需要新建topic；
4.3版本的MixAll.java
`public static final String AUTO_CREATE_TOPIC_KEY_TOPIC = "AUTO_CREATE_TOPIC_KEY";`
4.7版本的MixAll.java
   ` public static final String AUTO_CREATE_TOPIC_KEY_TOPIC = "TBW102"; `

至于说在启动的时候指定 autoCreateTopicEnable=true，已经没有必要了，至少我看4.3.0版本的源码，该属性值默认是true

**Comment by StrawberryCake-Fish** [comment]
已经 2025 年了，这个问题还是有，大佬们有解决方法吗，求教

**Comment by huansinho** [comment]
> 已经 2025 年了，这个问题还是有，大佬们有解决方法吗，求教

哈哈，确实是的，连不上也是No topic，没topic也是，好几个问题都是No topic这个错误。

**Comment by huangjuncong** [comment]
都快2026年了，这个报错还没解决吗？莫名其妙要创建重试队列，重试队列不是内部自动创建的吗？
