### ISSUE TITLE
使用控制台仪表盘时报错This date have't data!

### ISSUE THREAD

**Issue by clsaa** [apache/rocketmq-externals#211]
rmqconsole    | [2019-02-14 21:26:01.909] ERROR op=global_exception_handler_print_error
rmqconsole    | org.apache.rocketmq.console.exception.ServiceException: This date have't data!
rmqconsole    |         at org.apache.rocketmq.console.service.impl.DashboardCollectServiceImpl.getTopicCache(DashboardCollectServiceImpl.java:150)
rmqconsole    |         at org.apache.rocketmq.console.service.impl.DashboardServiceImpl.queryTopicData(DashboardServiceImpl.java:46)
rmqconsole    |         at org.apache.rocketmq.console.controller.DashboardController.topic(DashboardController.java:47)
rmqconsole    |         at sun.reflect.GeneratedMethodAccessor102.invoke(Unknown Source)
rmqconsole    |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
rmqconsole    |         at java.lang.reflect.Method.invoke(Method.java:498)
rmqconsole    |         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:220)
rmqconsole    |         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:134)
rmqconsole    |         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
rmqconsole    |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
rmqconsole    |         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
rmqconsole    |         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
rmqconsole    |         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
rmqconsole    |         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
rmqconsole    |         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
rmqconsole    |         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
rmqconsole    |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
rmqconsole    |         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
rmqconsole    |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:105)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)
rmqconsole    |         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
rmqconsole    |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
rmqconsole    |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
rmqconsole    |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
rmqconsole    |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
rmqconsole    |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
rmqconsole    |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
rmqconsole    |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
rmqconsole    |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
rmqconsole    |         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784)
rmqconsole    |         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
rmqconsole    |         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802)
rmqconsole    |         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410)
rmqconsole    |         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
rmqconsole    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
rmqconsole    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
rmqconsole    |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
rmqconsole    |         at java.lang.Thread.run(Thread.java:745)

**Comment by walking98** [comment]
The root cause of the error is the fact that the dashboard file is not generated:
check {rocketmq.config.dataPath}/dashboardYYYY-MM-DD_topic.json in your console runtime env
rocketmq.config.dataPath is defined in spring configuration file: application.properties

Is this directory correctly created in advance, by manual?

**Comment by vongosling** [comment]
@clsaa any update for your question?

**Comment by iyezhou** [comment]
解决：http://www.appblog.cn/2019/11/14/rocketmq-console%20%E9%83%A8%E7%BD%B2%E9%87%87%E5%9D%91%E8%AE%B0%E5%BD%95/
