### ISSUE TITLE
build rocketmq-console failed

### ISSUE THREAD

**Issue by xm-king** [apache/rocketmq-externals#212]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
when exec mvn clean package -Dmaven.test.skip in rocketmq-console, then faild:
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java:[22,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java:[23,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[23,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[24,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[25,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[26,40] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[29,47] 程序包org.apache.rocketmq.client.trace不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[29,1] 仅从类和接口静态导入
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[33,24] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java:[46,14] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.model.MessageTraceView
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java:[48,14] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.model.MessageTraceView
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/model/MessageTraceView.java:[50,13] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.model.MessageTraceView
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/controller/MessageTraceController.java:[68,32] 找不到符号
  符号:   变量 RMQ_SYS_TRACE_TOPIC
  位置: 类 org.apache.rocketmq.common.MixAll
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[34,14] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[34,52] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[38,63] 找不到符号
  符号:   变量 TraceConstants
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[40,58] 找不到符号
  符号:   变量 TraceConstants
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[41,32] 找不到符号
  符号:   变量 Pub
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[42,17] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[42,47] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[43,41] 找不到符号
  符号:   变量 Pub
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[47,17] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[47,38] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[63,56] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[66,48] 程序包TraceType不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[67,17] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[67,53] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[68,47] 找不到符号
  符号:   变量 TraceType
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[73,17] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[73,38] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[77,62] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[80,48] 程序包TraceType不存在
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[81,17] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[81,52] 找不到符号
  符号:   类 TraceContext
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[82,46] 找不到符号
  符号:   变量 TraceType
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[84,17] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[84,38] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[ERROR] /Users/xiangmin/workspace/rocketmq-externals/rocketmq-console/src/main/java/org/apache/rocketmq/console/util/MsgTraceDecodeUtil.java:[87,61] 找不到符号
  符号:   类 TraceBean
  位置: 类 org.apache.rocketmq.console.util.MsgTraceDecodeUtil
[INFO] 38 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.142 s
[INFO] Finished at: 2019-02-20T15:46:30+08:00
[INFO] Final Memory: 36M/508M
[INFO] ------------------------------------------------------------------------

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by walking98** [comment]
The dependency rocketmq.version has already been 4.4.0, please verify and close this issue. thx.
