### ISSUE TITLE
Is the development of iot bridge in progress?

### ISSUE THREAD

**Issue by apodemakeles** [apache/rocketmq-externals#218]
I really need a mqtt bridge based on rocketmq， open source，HA。Code in this repository only have in-memory functions, right? Will it be implemented one day?

**Comment by walking98** [comment]
please refer the mqtt subdirectory in RMQ main project (branch mqtt) https://github.com/apache/rocketmq/tree/mqtt

see if it will meet your requirement and open issues in main project for this if needed, thx.
