### ISSUE TITLE
[RocketMQ Console]Run error when using jdk10

### ISSUE THREAD

**Issue by salovexb** [apache/rocketmq-externals#225]
when the java_home is jdk10, java -jar rocketmq-console-ng-1.0.0.jar run jar failing, exception message like this: java.lang.ClassNotFoundException: javax.xml.bind.ValidationException. 
Add jaxb dependency and it runs fine.
<dependency>
		   <groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>javax.activation</groupId>
			<artifactId>activation</artifactId>
			<version>1.1.1</version>
		</dependency>

**Comment by walking98** [comment]
will look into this, the recommended runtime JDK is 8.

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading the to the latest spring-boot. You could use the latest code.
