### ISSUE TITLE
如何理解rocketmq-console的dashboard中的"5 min trend"数据？

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq-externals#228]
如下图，Broker 5 min trend 和 Topic 5 min trend这两个图的数据对应的语义什么呢？
我对比了下数据，既不是QPS，也不是5分钟内的消息量，不明白是什么意思。

![rocketmq-console](https://user-images.githubusercontent.com/3917749/54583778-3fd0d300-4a50-11e9-8f0e-2ad2f045205b.png)

**Comment by icersummer** [comment]
这两个图的意思是相近的, 一个在于表现 Broker, 一个在于表现 特定topic.

具体意思就是:  
当前时间点是 x分, 5分钟前是 (x-5) 分 , 以这两个时间点中 broker/topic 生产的消息的 总量, 除以 5, 得出 当前时间点的数值 (即5分钟内平均每分钟的生产消息量).


[https://blog.csdn.net/guofangsky/article/details/89065544](https://blog.csdn.net/guofangsky/article/details/89065544)

**Comment by hepyu** [comment]
非常感谢~~
