### ISSUE TITLE
Bug： Trace StoreHost are all console machine

### ISSUE THREAD

**Issue by ahuazhu** [apache/rocketmq-externals#235]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

  - Produce a message using client 4.4.0 with enableTrace=true
  - Consume the message using client 4.4.0 with enableTrace=true
  - Tracing the message in console web page.

- What did you expect to see?
 Expect to find the host on which the message produced and hosts which the message be consumed.

- What did you see instead?
All SubBefore and SubAfter show the store host of console Host.

2. Please tell us about your environment:

NA

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

NA

**Comment by imaffe** [comment]
Him storeHost should be the host that where the message is stored, which means the broker. If broker is node 1, producer is on node 2, consumer is on node 3, and console is on node 4, then the storeHost should be node1. Can you check if you are deploying both broker and console on the same machine ? Thanks so much for your follow up~
