### ISSUE TITLE
使用Docker方式启动RocketMQ，在远程访问不到Broker的问题

### ISSUE THREAD

**Issue by guowei1651** [apache/rocketmq-externals#238]
**BUG REPORT**
使用Docker-Compose启动RocketMQ。我需要在另外的主机上访问RocketMQ。这个时候发现没有办法进行NAT。

**FEATURE REQUEST**

**Comment by jackiehe2018** [comment]
I have the same problem to use this docker container too.

**Comment by vongosling** [comment]
@jackiehe2018 @guowei1651 please use the latest source to check
