### ISSUE TITLE
[Rocket Connector]Add An Empty RocketMQ Connector Module

### ISSUE THREAD

**Issue by zongtanghu** [apache/rocketmq-externals#242]
**FEATURE REQUEST**
1. Please describe the feature you are requesting.
A new module called rocketmq connector will be implemented for rocketmq message routing connector.

2. Provide any additional detail on your proposed use case for this feature.
In this pr,there is just an empty maven module.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
This module will be important to rocketmq message routing.

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by vongosling** [comment]
Done, I will close the issue.
