### ISSUE TITLE
The dlq topic default perm is 2, which makes it impossible to consume.

### ISSUE THREAD

**Issue by zlt2000** [apache/rocketmq-externals#265]
The dlq topic default perm is 2, which makes it impossible to consume.
![error](https://user-images.githubusercontent.com/30816365/56459066-535db980-63c1-11e9-9775-1599ad63f7ac.png)

Need to manually change to 6 to be able to consume normally
![success](https://user-images.githubusercontent.com/30816365/56459067-53f65000-63c1-11e9-8864-83db66fc1095.png)

**Comment by walking98** [comment]
Hi @zlt2000, the value of perm can be modified in "Topic配置" entry with the console.

**Comment by walking98** [comment]
In my verification, the perm value is "6" by default, and it can be modified using topic config. so it is not an issue. please close this. @zlt2000
