### ISSUE TITLE
rocketmq-jms integration support

### ISSUE THREAD

**Issue by wl105500396** [apache/rocketmq-externals#266]
Hi, I want to know if the rocketmq-jms is still supported and updated continuously. I downloaded the rocketmq-jms source codes and it appears just a few methods is implemented. Looking forward to your reply, thank you in advanced.

**Comment by vongosling** [comment]
@wl105500396 external projects almost come from the community, welcome any guys who have the desire to update some projects. The community would evaluate the maturity level to decide whether it is come out of the incubating status. that said, rocketmq-jms is obvious in this status, very glad to see you would participate in the update of this project.
