### ISSUE TITLE
Add .NET Client to RocketMQ

### ISSUE THREAD

**Issue by wlliqipeng** [apache/rocketmq-externals#273]
FEATURE REQUEST

Please describe the feature you are requesting.
.NET client for RocketMQ is wanted.

Provide any additional detail on your proposed use case for this feature.
The application system developed by .NET needs to send and receive messages through RocketMQ
More details
https://github.com/apache/rocketmq-externals/pull/217

**Comment by stephenmasih** [comment]
@wlliqipeng I am interested to contribute to this project as a part of Alibaba Summer of code 2019. Please help me design and fill-up the proposal.
