### ISSUE TITLE
Add PHP Client for RocketMQ

### ISSUE THREAD

**Issue by wlliqipeng** [apache/rocketmq-externals#274]
FEATURE REQUEST

Please describe the feature you are requesting.
PHP client for RocketMQ is wanted.

Provide any additional detail on your proposed use case for this feature.
The application system developed by PHP needs to send and receive messages through RocketMQ
More details
https://github.com/apache/rocketmq-externals/pull/215

**Comment by starcruizer** [comment]
Hi @wlliqipeng , I want to contribute to the above. Can you please guide me in preparing my proposal for 2019 Alibaba Summer of Code, since it is my first time in open source.

**Comment by wenzhi666** [comment]
请问点击申请链接之后，跳转到这个页面。怎么没有相关申请接口呢。

**Comment by ClementIV** [comment]
add user guide doc
