### ISSUE TITLE
docker of rocketmq-console-ng has lots of leaks

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq-externals#287]
docker of rocketmq-console-ng has lots of leaks as follows：

![image](https://user-images.githubusercontent.com/3917749/58409280-545dc700-80a2-11e9-98e0-3cbac3394916.png)

**Comment by walking98** [comment]
It is important direction to improve this security related features on next step. 
BTW what will the result if switching on the https + login auth?

**Comment by hepyu** [comment]
Switiching on the https+login auth is useless.

Because the leaks form aliyun examined were docker inside, different mirror Layers as follows。

![image](https://user-images.githubusercontent.com/3917749/58798811-33631c00-8636-11e9-9f07-373afb7fe55b.png)

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading the to the latest spring-boot. You could use the latest code to build a docker image. BTW, we are planning to add OWASP checker. If you have any question, please feel free to re-open the issue.
