### ISSUE TITLE
获取数据错误，不停的报错

### ISSUE THREAD

**Issue by cheriduk** [apache/rocketmq-externals#294]
环境：linux centOS6.8 rocketmq-all-4.2.0-source-release rocketmq-externals-master

以下错误一直滚动报错
ERROR op=global_exception_handler_print_error
org.apache.rocketmq.console.exception.ServiceException: This date have't data!
	at org.apache.rocketmq.console.service.impl.DashboardCollectServiceImpl.getBrokerCache(DashboardCollectServiceImpl.java:140)

ERROR op=global_exception_handler_print_error
org.apache.rocketmq.console.exception.ServiceException: This date have't data!

**Comment by walking98** [comment]
This is unfriendly log info, which means the console API can not get the consume/produce messages on the given date. 

The API is invoked repeatedly by a timer, so these ERROR log message always print

**Comment by iyezhou** [comment]
解决：http://appblog.cn/2019/11/14/rocketmq-console%20%E9%83%A8%E7%BD%B2%E9%87%87%E5%9D%91%E8%AE%B0%E5%BD%95/
