### ISSUE TITLE
[Flink] Sending and consumption messages to/from different clusters

### ISSUE THREAD

**Issue by ahuazhu** [apache/rocketmq-externals#306]
The issue tracker is **ONLY** used for bug report and feature request. 

**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Sending and consumption message to/from different clusters.

2. Provide any additional detail on your proposed use case for this feature.
When a job consumes messages from ClusterA and sends messages to ClusterB. Because Flink operators may be chained, the consumer and producer is possible running in the same JVM process. The default instanceName creator creates the same instanceName for the producer and consumer, then the messages will be not sent to the ClusterB.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
blocker

**Comment by vesense** [comment]
Thanks @ahuazhu I will take a look tonight.
