### ISSUE TITLE
[RocketMQ-Console] Allow remove monitor

### ISSUE THREAD

**Issue by Adol1111** [apache/rocketmq-externals#317]
Add a monitor for SubscriptionGroup, but can not remove it If i don't need this conumser group.

目前只能添加monitor，但如果这个group已经不再使用，消息存在积压，告警无法消除，会一直持续告警。

比如一个topic，有两个消费group，其中一个不再使用，但仍然有生产（另一个消费者在消费），offset会一直上涨，最后触发告警，目前好像取消不掉。

**Comment by chenxubiao** [comment]
我目前是直接请求接口进行删除
`org.apache.rocketmq.console.controller.MonitorController#deleteConsumerMonitor`

**Comment by francisoliverlee** [comment]
@Adol1111 @chenxubiao 
now we have RocketMQ Exporter to monitor the whole RocketMQ cluster、producer and consumer, simple and a lot of metrics you should need
code is here : [RocketMQ Exporter ](https://github.com/apache/rocketmq-exporter)
