### ISSUE TITLE
.NET Client执行时报错

### ISSUE THREAD

**Issue by JarvanZhou** [apache/rocketmq-externals#340]
测试时var producerPtr = ProducerWrap.CreateProducer("xxx");这句报错,
提示:System.DllNotFoundException:“Unable to load DLL 'rocketmq-client-cpp.dll' or one of its dependencies: 找不到指定的模块
是要安装什么依赖吗?

**Comment by ClementIV** [comment]
这个是rocketmq-client-cpp.dll 缺失，已经在pr里面解决[Add .Net Client](https://github.com/apache/rocketmq-externals/pull/334),如果您需要，可以使用Nuget包[rocketmq-client-dotnet](https://www.nuget.org/packages/rocketmq-client-dotnet/)，或者等待pr完成

**Comment by wjwei323** [comment]
Nuget包也会报这个错误

**Comment by ClementIV** [comment]
> Nuget包也会报这个错误

可以参考如下文档

https://github.com/ClementIV/rocketmq-externals/blob/master/rocketmq-client-dotnet/docs/QuickStart.md

**Comment by cheewen0430** [comment]
> > Nuget包也会报这个错误
> 
> 可以参考如下文档
> 
> https://github.com/ClementIV/rocketmq-externals/blob/master/rocketmq-client-dotnet/docs/QuickStart.md

这文档已关闭, 可是我找到另一个文档，是这个吗？
>> https://github.com/ClementIV/rocketmq-client-dotnet/blob/master/docs/QuickStart.md
