### ISSUE TITLE
No namesrvAdd was showed in the browse after I put rocketmq-console into k8s

### ISSUE THREAD

**Issue by hepyu** [apache/rocketmq-externals#409]
There some wired phenomenon after I put rocketmq-console into k8s as below:
No namesrvAdd was showed in the browse, but async http response workd and get response about namesrvAdd message，is there some js bug ?

![image](https://user-images.githubusercontent.com/3917749/64098993-c9742300-cd9a-11e9-8fc0-69cbbe96b9bf.png)

**Comment by imaffe** [comment]
Did you tried to refresh the homepage ? Update namesrv address only returns true/false and will not refresh the page. Only when we reload the home page the newest namesrv list will be displayed
```
    $http({
        method: "GET",
        url: "ops/homePage.query"
    }).success(function (resp) {
        if (resp.status == 0) {
            $scope.namesvrAddrList = resp.data.namesvrAddrList;
            $scope.useVIPChannel = resp.data.useVIPChannel
        }else{
            Notification.error({message: resp.errMsg, delay: 2000});
        }
    });
```
