### ISSUE TITLE
[rocketmq-console] message trace message detail:CODE: 208 DESC: query message by key finished, but no message.

### ISSUE THREAD

**Issue by cocodroid** [apache/rocketmq-externals#410]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
view message trace message detail occur:CODE: 208 DESC: query message by key finished, but no message.
- What did you do (The steps to reproduce)?

- What did you expect to see?
see meesage detail
- What did you see instead?
CODE: 208 DESC: query message by key finished, but no message.
2. Please tell us about your environment:
rocketmq v-4.4   rocketmq-console v-1.0.1
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
I doubt that the msgId is error, it should be key ?

**Comment by cocodroid** [comment]
If if may be occured , if I use async send message

**Comment by cocodroid** [comment]
Now, I find it will happened when the Tab is Message Key. And why?

**Comment by Shellbye** [comment]
I find it will happended too when the Tab is Message ID. After I go through some source code, I find the Message Id should be `offsetMsgId`.

**Comment by jierfei1007** [comment]
i use this class DefaultMQAdminExt defaultMQAdminExt = new DefaultMQAdminExt("***")
and use this function public MessageExt viewMessage(String topic, String msgId) to get MessageExt
but sometimes got error "CODE: 208  DESC: query message by key finished, but no mess
age"  sometimes is ok

**Comment by simonton** [comment]
> view message trace message detail occur:CODE: 208 DESC: query message by key finished, but no message.
It could get 208 CODE when mqbroker do not enable traceTopicEnable ,  please make sure  traceTopicEnable=true in broker config file

**Comment by fibbery** [comment]
#572 
same question

**Comment by maixiaohai** [comment]
Same situation using console-2.0.0 & rmq 4.7.0
Can I submit a PR to fix this?
Or the community have done it?

**Comment by YAGAMIL** [comment]
> 使用控制台-2.0.0和rmq 4.7.0
> 相同的情况，我可以提交一个公关来解决这个问题吗？
> 还是社区都做了？
我也碰到了这样的问题

**Comment by heart4lor** [comment]
> Same situation using console-2.0.0 & rmq 4.7.0
> Can I submit a PR to fix this?
> Or the community have done it?

@maixiaohai Hey, have you solved the problem yet? is the [unique key issue](https://github.com/apache/rocketmq/issues/572) or [producer & broker time syncing issue](https://github.com/apache/rocketmq-externals/issues/681)? Thanks.

**Comment by maixiaohai** [comment]
> > Same situation using console-2.0.0 & rmq 4.7.0
> > Can I submit a PR to fix this?
> > Or the community have done it?
> 
> @maixiaohai Hey, have you solved the problem yet? is the [unique key issue](https://github.com/apache/rocketmq/issues/572) or [producer & broker time syncing issue](https://github.com/apache/rocketmq/issues/681)? Thanks.

It's my usage problem, trace query work fine.
