### ISSUE TITLE
query message by rocektmq console has Exception

### ISSUE THREAD

**Issue by kangjiabang** [apache/rocketmq-externals#459]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
  rocketmq console report InvocationException when query message detail.
- What did you do (The steps to reproduce)?
   
![image](https://user-images.githubusercontent.com/25074646/68366616-b56be980-016e-11ea-8c54-da4097107ec1.png)

- What did you expect to see?
  message detail
- What did you see instead?
  
![image](https://user-images.githubusercontent.com/25074646/68366636-c1f04200-016e-11ea-8aab-4c0222d29729.png)

2. Please tell us about your environment:
    java: jdk1.8.
    console:  rocketmq-console-ng-1.0.0-snapshot
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
    console error logs:
    
![image](https://user-images.githubusercontent.com/25074646/68366787-1e536180-016f-11ea-8e81-b16443df3d62.png)

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by fibbery** [comment]
#572 
same question

**Comment by hydra0o** [comment]
same question ,Do you have an answer？
