### ISSUE TITLE
The behavior of the cluster store topic leads to confusion

### ISSUE THREAD

**Issue by ShadowySpirits** [apache/rocketmq-externals#465]
When broker's setting item autoCreateTopicEnable is true, configStoreTopic、positionStoreTopic、offsetStoreTopic will be created automatically. When autoCreateTopicEnable is false, there will be a topic not exist exception.
But clusterStoreTopic won't be created and no warning whatever autoCreateTopicEnable is.

**Comment by lexingrensheng** [comment]
you can try fix
