### ISSUE TITLE
Failed to query message

### ISSUE THREAD

**Issue by Attzsthl** [apache/rocketmq-externals#471]
1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
when i wang to query message by rocketmq console

- What did you expect to see?
message detail

- What did you see instead?
org.apache.rocketmq.console.exception.ServiceException: Failed to query message by Id

2. Please tell us about your environment:
rocketmq 4.4.0-release deployed in aliyun
use acl

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**
i can't see topic also, can only see consumer
![image](https://user-images.githubusercontent.com/33572220/69775783-db683500-11d4-11ea-8f92-ee40ab16ebe7.png)

**Comment by zhuyaoming** [comment]
I can see mesage list  but cannot see message detail info

**Comment by zhuyaoming** [comment]
> I can see mesage list but cannot see message detail info

i solve it  thanks

**Comment by bighong0404** [comment]
@zhuyaoming 老哥你是怎么处理的, 我也遇到这bug

**Comment by lizhen1412** [comment]
I have this problem, too
![AA64596A-E38D-40B1-903F-61FC74ED99AB](https://user-images.githubusercontent.com/29331541/74103381-983c2200-4b86-11ea-8aef-0f1870849058.png)

**Comment by bingxe-fengbenwu** [comment]
@zhuyaoming @lizhen1412 @bighong0404 How to solve.怎么搞定的，我没找到问题

**Comment by qingruihappy** [comment]
> @zhuyaoming @lizhen1412 @bighong0404 How to solve.怎么搞定的，我没找到问题所在，求解答

**Comment by qingruihappy** [comment]
解决了吗

**Comment by zhoufanshou** [comment]
楼主的问题解决了吗

**Comment by zhoufanshou** [comment]
我出现的问题是最近的可以正常显示，时间比较久的无法显示

**Comment by lizhen1412** [comment]
有截图吗
&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhoufanshou"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月11日(星期四) 上午10:45
收件人:&nbsp;"apache/rocketmq-externals"<rocketmq-externals@noreply.github.com&gt;;
抄送:&nbsp;"云之雪"<595265454@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [apache/rocketmq-externals] Failed to query message (#471)





 
我出现的问题是最近的可以正常显示，时间比较久的无法显示

**Comment by zhoufanshou** [comment]
> 有截图吗 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"zhoufanshou"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月11日(星期四) 上午10:45 收件人:&nbsp;"apache/rocketmq-externals"<rocketmq-externals@noreply.github.com&gt;; 抄送:&nbsp;"云之雪"<595265454@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [apache/rocketmq-externals] Failed to query message (#471) 我出现的问题是最近的可以正常显示，时间比较久的无法显示 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
第一张图是2020-05-01产生的信息，第二张图是今天产生的信息，第一张查看详情报错，第二张正常
![image](https://user-images.githubusercontent.com/41277489/84366777-e715c900-ac05-11ea-8a8f-93f82f309259.png)
![image](https://user-images.githubusercontent.com/41277489/84366822-f39a2180-ac05-11ea-8634-93622dafab7c.png)
