### ISSUE TITLE
message trace bug of console: timestamp is now at subAfter record

### ISSUE THREAD

**Issue by faryang-sh** [apache/rocketmq-externals#480]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/14032423/70375760-db86d400-193c-11ea-8ef4-e6023574635c.png)
消息轨迹查询中，对于subAfter的消息记录内容中是没有时间的，而查询结果显示是当前时间。
- What did you do (The steps to reproduce)?

- What did you expect to see?
subAfter的消息记录中storeTime应该为空
- What did you see instead?

2. Please tell us about your environment:
macOS 10.14 
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by faryang-sh** [comment]
PR : https://github.com/apache/rocketmq-externals/pull/479

**Comment by imaffe** [comment]
Hi, the storeTime here should be the storeTime of the non-tracing message. So the store time here should not be null. Notice storeTime is not the time when the trace message got stored to commitLog, but the time when the message that triggered the trace message is stored
