### ISSUE TITLE
请给一个连接aliyun商业云的demo，谢谢。

### ISSUE THREAD

**Issue by skywoodsky** [apache/rocketmq-externals#49]
DefaultMQPushConsumer consumer("CID_JfSiteConsume");
	consumer.setSessionCredentials("×××××", "×××××", "ALIYUN");
	consumer.setConsumeFromWhere(CONSUME_FROM_LAST_OFFSET);
//	consumer.setMessageModel(BROADCASTING);
	consumer.setNamesrvAddr("http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet");

//	consumer.setGroupName("CID_JfSiteConsume");
//	consumer.setNamesrvDomain(info.namesrv_domain);
//	consumer.setInstanceName("CID_JfSiteConsume");
	MyMsgListener msglistener;
	consumer.registerMessageListener(&msglistener);
	consumer.subscribe("SiteInformMessage", "*");

	try
	{
		consumer.start();
	}
	catch (MQClientException &e) 
	{
		std::cout << e << std::endl;
	}

	std::cout << "consumer started";
	std::string str;
	std::cin >> str;

	consumer.shutdown();
这是我的测试代码，无法收到消息。

**Comment by vincentWangKB** [comment]
hi, 这里有完整的接入信息： https://help.aliyun.com/document_detail/55448.html?spm=a2c4g.11186623.6.579.x06rYN

**Comment by skywoodsky** [comment]
这是针对aliyun的sdk的，接口和开源sdk不一样。

**Comment by vincentWangKB** [comment]
你是想用c++的SDK吗？

**Comment by skywoodsky** [comment]
是的。


发自网易邮箱大师
在2018年3月21日 10:12，vincent wang<notifications@github.com> 写道：

你是想用c++的SDK吗？

**Comment by vincentWangKB** [comment]
你上面贴出来的代码，收不到消息是因为下面两个原因：
1. consumer启动后马上被shutdown了
2. MyMsgListener msglistener 被释放了

有两个注意的点：
1. 整个消费过程中consumer不能被shutdown，msglistener不能被释放
2. setSessionCredentials要配置好aliyun的ak，sk

**Comment by vincentWangKB** [comment]
可以参考rocketmq-cpp/example/PushConsumer的做法

**Comment by skywoodsky** [comment]
我的测试代码就是参考它写的

**Comment by skywoodsky** [comment]
而且的example/PushConsumer 里，也没说明哪里填 ConsumerId
你直接看下我的测试代码，看看有什么地方不对吧

**Comment by skywoodsky** [comment]
我的测试代码，不会马上shutdown的，会等待控制台输入的

**Comment by skywoodsky** [comment]
std::cin >> str;

consumer.shutdown();

**Comment by skywoodsky** [comment]
accesskey和secretkey已配置，我贴代码时隐藏了

**Comment by vincentWangKB** [comment]
consumer.setNamesrvAddr("http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet");
这一行应该改成：
consumer.setNamesrvDomain(("http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet");

然后注意：整个消费过程中consumer不能被shutdown，msglistener不能被释放，你的代码里msglistener是个局部变量，不要超出作用域被释放了，这里要注意

**Comment by skywoodsky** [comment]
谢谢，现在已经能收到消息了。
但是在控制台查看消息轨迹时，无法看到消息已被消费。

**Comment by skywoodsky** [comment]
这是我的messagelistener代码
class MyMsgListener : public MessageListenerConcurrently {
public:
	MyMsgListener() {}
	virtual ~MyMsgListener() {}

	virtual ConsumeStatus consumeMessage(const std::vector<MQMessageExt> &msgs) {
		for (size_t i = 0; i < msgs.size(); ++i) 
		{
			std::cout << msgs[i].getTopic() << std::endl;
			std::cout << msgs[i].getTags() << std::endl;
			std::cout << msgs[i].getBody() << std::endl;
		}

		return CONSUME_SUCCESS;
	}
};
