### ISSUE TITLE
org.apache.rocketmq.remoting.exception.RemotingConnectException: connect to <192.168.228.101:9876> failed

### ISSUE THREAD

**Issue by changelzj** [apache/rocketmq-externals#513]
For the same cluster, this is how I configured it. The firewall is closed and there is no port conflict

nameserver1 : 192.168.228.101:9876
nameserver2 : 192.168.228.103:9876

2m-2s-sync

 192.168.228.101 ：   broker-name:a,master          broker-name:b,slave
 192.168.228.103   ：broker-name:b,master          broker-name:a,slave

**Comment by francisoliverlee** [comment]
use
```bash
 telnet ip port 
```
to check if the socket is connectable or not

**Comment by Uetty** [comment]
同，求解
![image](https://user-images.githubusercontent.com/14183559/95543176-67203400-0a2a-11eb-8694-066e0df329b0.png)

![image](https://user-images.githubusercontent.com/14183559/95543193-71dac900-0a2a-11eb-9f7a-059cddf6053f.png)

**Comment by Uetty** [comment]
![image](https://user-images.githubusercontent.com/14183559/95543254-9cc51d00-0a2a-11eb-85d3-82497cd078db.png)

**Comment by Uetty** [comment]
> 同，求解
> ![image](https://user-images.githubusercontent.com/14183559/95543176-67203400-0a2a-11eb-8694-066e0df329b0.png)
> 
> ![image](https://user-images.githubusercontent.com/14183559/95543193-71dac900-0a2a-11eb-9f7a-059cddf6053f.png)


发现原因所在了，解答一下：
因为我拉取的console项目是最新的版本【2.0.0】的console，对应的rocketmq core是【4.7.1】，而我namesrv和broker服务器使用的是【4.3.2】版本的core。改成使用【1.0.0】的RELEASE版本console（对应的rocketmq core是【4.0.0-incubating】）之后，就能正常启动console了，估计是两个版本协议有点区别。
