### ISSUE TITLE
[rocketmq-flink] MQPullConsumerScheduleService registerPullTaskCallback handles namespace incorrectly

### ISSUE THREAD

**Issue by Marsyyh** [apache/rocketmq-externals#514]
**BUG REPORT**

1. Please describe the issue you observed:
pullConsumerScheduleService.registerPullTaskCallback will cause "Pull task callback not exists warning"

- What did you do (The steps to reproduce)?
Run the example

- What did you expect to see?
Example works

- What did you see instead?
Pull task callback not exists warning

2. Please tell us about your environment:
    javaVersion = '1.8'
    flinkVersion = '1.9.0'
    scalaBinaryVersion = '2.11'
    rocketmqVersion = '4.5.2'
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
    rocketmq client suggest using new lite pull consumer instead of MQPullConsumerScheduleService https://github.com/apache/rocketmq/issues/1512

**Comment by RongtongJin** [comment]
link rocketmq pr [1804](https://github.com/apache/rocketmq/pull/1804)
