### ISSUE TITLE
dont support java 8 localdatetime?

### ISSUE THREAD

**Issue by ghjhf** [apache/rocketmq-externals#528]
![image](https://user-images.githubusercontent.com/17490562/76839847-38195980-6871-11ea-8644-9960c6d8818f.png)
![image](https://user-images.githubusercontent.com/17490562/76839916-52533780-6871-11ea-81a0-df765a01dda1.png)
![image](https://user-images.githubusercontent.com/17490562/76839957-672fcb00-6871-11ea-83fe-007150f53ca3.png)

**Comment by vongosling** [comment]
This is a similar report in RocketMQ spring.
