### ISSUE TITLE
[rocketmq-connect-jdbc runtime error : NoClassDefFoundError]

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#535]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?
1. run rocketmq-connect-runtime
2. try to start rocketmq-connect-jdbc source and sink connectors
- What did you expect to see?
Run without error
- What did you see instead?
```
java.lang.NoClassDefFoundError: org/apache/rocketmq/tools/admin/DefaultMQAdminExt
	at org.apache.rocketmq.connect.jdbc.connector.JdbcSinkConnector.startMQAdminTools(JdbcSinkConnector.java:55)
```
2. Please tell us about your environment:

ubuntu server 16.04 lts
java 8
rocketmq-connect: 0.0.1 snapshot
roccketmq-connect-jdbc: rocketmq-connect-jdbc-0.0.1-SNAPSHOT.jar
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

Because it's a NoClassDefFoundError, so I guess it's because `import org.apache.rocketmq.tools.admin.DefaultMQAdminExt` and `org.apache.rocketmq.tools` is not in class path when runtime starts. I checked the ./lib of runtime, and found there is only

```
ll ~/rocketmq-externals/rocketmq-connect/rocketmq-connect-runtime/target/distribution/lib
# output
...
-rw-rw-r-- 1 affe affe  333224 Mar 25 06:25 rocketmq-client-4.5.2.jar
-rw-rw-r-- 1 affe affe  284472 Mar 25 06:25 rocketmq-common-4.5.2.jar
-rw-rw-r-- 1 affe affe  134940 Mar 25 06:25 rocketmq-connect-runtime-0.0.1-SNAPSHOT.jar
-rw-rw-r-- 1 affe affe   63747 Mar 25 06:25 rocketmq-logging-4.5.2.jar
-rw-rw-r-- 1 affe affe  121105 Mar 25 06:25 rocketmq-remoting-4.5.2.jar
...
```
So maybe add `rocketmq-tools-4.x.x.jar` should solve the problem. But since they are all within the rocketmq artifact, I don't know how to find the  `rocketmq-tools-4.x.x.jar`. I guess `rocketmq-tools` was added recently? Hope this helps :)

**Comment by duhenglucky** [comment]
@imaffe https://github.com/apache/rocketmq/tree/master/tools
