### ISSUE TITLE
[rocketmq-connect-runtime] Update the version

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#536]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

rocketmq-connect-jdbc relies on rocketmq 4.7.0, but rocketmq-connect-runtime only provides 4.5.2

I would appreciate it so much if someone can assign this to me as this is finally something I can fix LOL.

**Comment by duhenglucky** [comment]
@imaffe welcome to submit a PR.

**Comment by imaffe** [comment]
Sure, will be on this tomorrow, ( preparing for the interview LOL)

**Comment by imaffe** [comment]
Solved in PR 537
