### ISSUE TITLE
[rocketmq connect gitbook] We can put the rocketmq connect gitbook here

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#547]
**FEATURE REQUEST**

1. If we can put the rocketmq connect [gitbook](https://rocketmq-1.gitbook.io/rocketmq-connector/) documentation under this repo, we can start to contribute to the documentation while reading the source code and debugging connector, which would be nice~

**Comment by ClementIV** [comment]
Thank you for your advice. I will finish this task in the near future.

**Comment by gripson** [comment]
May I ask if you will submit PR to merge your gitbook docs to the `apache/rocketmq-externals` ? 
@ClementIV

**Comment by ClementIV** [comment]
Yep! @gripson

**Comment by gripson** [comment]
@ClementIV Thanks :)
