### ISSUE TITLE
[rocketmq-console-ng] Update the official recommend docker image styletang/rocketmq-console-ng

### ISSUE THREAD

**Issue by wohenbushuang** [apache/rocketmq-externals#566]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Update the official recommend docker image [styletang/rocketmq-console-ng](https://hub.docker.com/r/styletang/rocketmq-console-ng)
2. Provide any additional detail on your proposed use case for this feature.
Last update was on 3 years ago
2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
must-have

**Comment by imaffe** [comment]
Sure, we are working on this ~ We are planning to migrate the recommended image to the official dockerhub account

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading to the latest spring-boot. You could use the latest code to build the image.
