### ISSUE TITLE
Improvements for RocketMQ-Spark

### ISSUE THREAD

**Issue by vesense** [apache/rocketmq-externals#57]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

Some improvements for RocketMQ-Spark.

2. Provide any additional detail on your proposed use case for this feature.

Following is the change list:
* Upgraded RocketMQ version to 4.2.0
* Removed duplicated gitignore
* Removed author infos
* Enabled unit tests by default
* Removed the dependency of java class refer to scala `RocketMqUtils`
* Moved `RocketMqRDD` and `MQPullInputDStream` to the right directory. These two class should be in the `org.apache.spark` package due to the limit of being invoked APIs `private[spark]`.
* Some minor code style and documents improvements

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

must-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- no sub tasks

**Comment by vesense** [comment]
@vongosling Updated issue by template.

**Comment by vongosling** [comment]
cool
