### ISSUE TITLE
MQAdminExtImpl不是抽象的

### ISSUE THREAD

**Issue by TangGe2010** [apache/rocketmq-externals#580]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

- What did you do (The steps to reproduce)?

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by TangGe2010** [comment]
pom.xml里把rocketmq升级为4.7版本后。报错Error:(72, 8) java: org.apache.rocketmq.console.service.client.MQAdminExtImpl不是抽象的, 并且未覆盖org.apache.rocketmq.tools.admin.MQAdminExt中的抽象方法resumeCheckHalfMessage(java.lang.String,java.lang.String)

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading the to the latest spring-boot. You could use the latest code https://github.com/apache/rocketmq-externals/pull/600
