### ISSUE TITLE
 rocketmq-console running failed

### ISSUE THREAD

**Issue by yejiahao** [apache/rocketmq-externals#599]
**BUG REPORT**

- When I fetch and merge the latest commit, and try to run rocketmq-console,
```
$ git fetch && git merge
$ nohup java -jar rocketmq-console-ng-2.0.0.jar --server.port=6789 --rocketmq.config.namesrvAddr=localhost:9876 &
```
it failed, log file appends:
```
no main manifest attribute, in rocketmq-console-ng-2.0.0.jar
```

**Comment by vongosling** [comment]
Thanks for your report. We are upgrading the to the latest spring-boot. You could use the latest code https://github.com/apache/rocketmq-externals/pull/600
