### ISSUE TITLE
RocketMQ 监控查看消费情况报错206

### ISSUE THREAD

**Issue by jinglongjun** [apache/rocketmq-externals#60]
RocketMQ 查看消费者消费情况 ，请求如下：

> /consumer/queryTopicByConsumer.query?consumerGroup=BIZ_LOG_ONS_PRODUCER_GROUP

报错内容：

> {"status":-1,"data":null,"errMsg":"org.apache.rocketmq.client.exception.MQClientException: CODE: 206  DESC: Not found the consumer group consume stats, because return offset table is empty, maybe the consumer not consume any message\nFor more information, please visit the url, http://rocketmq.apache.org/docs/faq/"}

实际的faq页面没找到相关的信息。

**Comment by vongosling** [comment]
The issue tracker is ONLY used for bug report and feature request. Alternately (especially if your communication is not a bug report), you can send mail to our mailing lists.http://rocketmq.apache.org/about/contact/

**Comment by igoqhb1990** [comment]
我也遇到了同样的问题，怎么解决呢？
