### ISSUE TITLE
[rocketmq-connect-runtime] paused tasks are still pulling from RocketMQ and discarding messages

### ISSUE THREAD

**Issue by imaffe** [apache/rocketmq-externals#612]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

1. when a task is paused, we expect it to stop fetching data from RocketMQ, however in current implementation, the paused tasks are fetching data and discarding them, which would lead to data lose (and user wouldn't expect to lose data when they click a pause button)

```
            if (pullResult.getPullStatus().equals(PullStatus.FOUND)) {
                final List<MessageExt> messages = pullResult.getMsgFoundList();
                // removePausedQueueMessages
                receiveMessages(messages);
                messageQueuesOffsetMap.put(entry.getKey(), pullResult.getNextBeginOffset());
                offsetData.put(convertToByteBufferKey(entry.getKey()), convertToByteBufferValue(pullResult.getNextBeginOffset()));
                preCommit();
            }
```

**Comment by odbozhou** [comment]
![image](https://user-images.githubusercontent.com/14222167/130403841-8b892db8-9c16-4eca-a6a5-95399ed59401.png)
The latest version of the code, if the task is not in the RUNNING state, the message will not be pulled.
If you still have problems, you can reopen this issue
