### ISSUE TITLE
[rocketmq-console] 开启认证登录后访问页面出现无限302

### ISSUE THREAD

**Issue by gengweifeng** [apache/rocketmq-externals#614]
根据[说明文档](https://github.com/apache/rocketmq-externals/blob/master/rocketmq-console/doc/1_0_0/UserGuide_CN.md)配置了用户名密码认证方式，配置完成后访问主页面出现重复重定向导致页面打开失败

配置如下：

application.properties:
    server.address=0.0.0.0
    server.port=8080
    spring.http.encoding.charset=UTF-8
    spring.http.encoding.enabled=true
    spring.http.encoding.force=true
    logging.config=classpath:logback.xml
    rocketmq.config.namesrvAddr=rocketmq-n-1.default:9876
    rocketmq.config.loginRequired=true
    rocketmq.config.dataPath=/tmp/rocketmq-console/data

users.properties:
    admin=admin,1
    user=user,0

浏览器地址栏访问console页面 http://localhost:8080 ，地址栏出现 http://localhost:8080/#/login?redirect=http%3A%2F%2Flocalhost%3A8080%2F ，并且提示重定向次数过多，无法访问，未出现期望的登录页面

rocketmq使用的版本是4.3.2，rocketmq-console版本是最新的2.0.0

**Comment by imaffe** [comment]
This is indeed a bug. After server redirects the browser to  http://example.com/#/login?redirect=XXX, the angular js would send a request to /views/pages/login.html, which is in the auth filter path, and it will be redirect again....  Currently we think there is a big problem of using user login and we are fixing it. Before we have any updates, we do not recommend set rocketmq.config.loginRequired=true at this time. Thanks for this bug report ~

**Comment by xingfudeshi** [comment]
It seems that the image of docker hub has not been updated.
