### ISSUE TITLE
Add javadocs for RocketMQ-Spark

### ISSUE THREAD

**Issue by vesense** [apache/rocketmq-externals#62]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

I think it's very necessary to add javadocs since it would be convenient to learn the API usage for RocketMQ users, especially the fresh.

2. Provide any additional detail on your proposed use case for this feature.

* Add `maven-javadoc-plugin` in pom.xml
* Add `javadocs` directory including the lateset javadoc.
* Update the rocketmq-spark/README.md

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

should-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- no sub task

**Comment by vongosling** [comment]
Why open this issue here. If we hope to polish here, we could make the issue more clear:-）
