### ISSUE TITLE
[rocketma-knative-source] error Send cloud event %s error sending cloudevent: 415 Unsupported Media Type

### ISSUE THREAD

**Issue by pengcheng-cs** [apache/rocketmq-externals#629]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:

Pod of RocketMQSource can consume message from RocketMQ, but meets error Send cloud event %s error sending cloudevent: 415 Unsupported Media Type

RocketMQSource defined like this image
![image](https://user-images.githubusercontent.com/5285226/90717206-a7dcb600-e2e1-11ea-868d-2d2acb351b19.png)

Also event-display service didn't receive any events from RocketMQSource

- What did you do (The steps to reproduce)?

1. Install Knative eventing 0.14.2
2. Follow steps of RocketMQ Source [README.md](https://github.com/apache/rocketmq-externals/blob/master/rocketmq-knative/source/README.md) 

- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

Knative Eventing@0.14.2

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

Logs 
subscribe callback: [Message=[topic=faas-eventing-test, body={ "index": 0, "key": "user_ip", "label": "IP", "value": "10.209.xxx" }, Flag=0, properties=map[APP_ENV_NAME:* CLUSTER:DefaultCluster CONSUME_START_TIME:159789xxx KEYS:* MAX_OFFSET:1 MIN_OFFSET:0 TAGS:* UNIQ_KEY:AC1C7A110xxxx WAIT:true], TransactionId=], MsgId=0A010DBD0000xxx, QueueId=2, StoreSize=287, QueueOffset=0, SysFlag=0, BornTimestamp=1597895679328, BornHost=172.28.xxx:42692, StoreTimestamp=1597895679332, StoreHost=10.1.xxx:10911, CommitLogOffset=52119833194, BodyCRC=1656014428, ReconsumeTimes=0, PreparedTransactionOffset=0] 
error Send cloud event %s error sending cloudevent: 415 Unsupported Media Type

**Comment by vongosling** [comment]
CloudEvents type is not fully supported now. Would you like to perfect it? I'll follow up.
