### ISSUE TITLE
[rocketmq-flink] flinksql connector rocketmq

### ISSUE THREAD

**Issue by RoadOfShang** [apache/rocketmq-externals#631]
hope the community provide a connection that can be well integrated with FlinkSQL。
be similar to kafka:

CREATE TABLE kafkaTable (
 user_id BIGINT,
 item_id BIGINT,
 category_id BIGINT,
 behavior STRING,
 ts TIMESTAMP(3)
) WITH (
 'connector' = 'kafka',
 'topic' = 'user_behavior',
 'properties.bootstrap.servers' = 'localhost:9092',
 'properties.group.id' = 'testGroup',
 'format' = 'csv',
 'scan.startup.mode' = 'earliest-offset'
)

**Comment by francisoliverlee** [comment]
do u like to submit a PR to do with it?

**Comment by RoadOfShang** [comment]
> do u like to submit a PR to do with it?


I'm solving this problem, but I don't know if I can get a good result

**Comment by stevenchange** [comment]
hello，do you solve this problem?
I'm working on this.

can I try this?

**Comment by stevenchange** [comment]
the demo like this:
"CREATE TABLE datagen ( \n" +
"  f_sequence INT, \n" +
"  f_random INT, \n" +
"  f_random_str STRING \n" +
") WITH ( \n" +
"  'connector' = 'rmq-flink',\n" +
"  'topic' = '" + topic + "', \n" +
"  'nameserver.address' = '" + nameServer + "', \n" +
"  'group' = 'connector', \n" +
"  'format' = 'rmq-json' \n" +
")";

**Comment by vongosling** [comment]
sure @stevenchange  I am glad to follow your pr.

**Comment by stevenchange** [comment]
thanks， @vongosling 
I will create a new issue ,please assign this issue to me.

**Comment by vongosling** [comment]
Just do it. We just link pr and issue.
