### ISSUE TITLE
[rocketmq-flink] flinksql connector rocketmq

### ISSUE THREAD

**Issue by stevenchange** [apache/rocketmq-externals#638]
provide a connection that can be well integrated with FlinkSQL。
be similar to kafka:

CREATE TABLE kafkaTable (
user_id BIGINT,
item_id BIGINT,
category_id BIGINT,
behavior STRING,
ts TIMESTAMP(3)
) WITH (
'connector' = 'kafka',
'topic' = 'user_behavior',
'properties.bootstrap.servers' = 'localhost:9092',
'properties.group.id' = 'testGroup',
'format' = 'csv',
'scan.startup.mode' = 'earliest-offset'
)

**Comment by stevenchange** [comment]
@vongosling could you assign this issue to me?

**Comment by vongosling** [comment]
You could open the pr and link this issue by yourself :-) This is not like the Jira process.

**Comment by stevenchange** [comment]
thanks.

I was testing code。
I will pull request a few days
