### ISSUE TITLE
RocketMQ-Console消息轨迹的MESSAGE ID --> StoreHost是Console部署机器的地址

### ISSUE THREAD

**Issue by xiangyang-gao** [apache/rocketmq-externals#639]
Message ID | Tag | Message Key | StoreTime | StoreHost | costTime | status | traceType
-- | -- | -- | -- | -- | -- | -- | --
AC170430291518B4AAC24B54A00B0267 | null | null | 2020-10-15 15:03:57 | 192.168.31.19:10911 | 12ms | Sucess
AC170430291518B4AAC24B54A00B0267 |   | null | 2020-10-15 15:03:57 | 192.168.31.49 | 0ms | Sucess
AC170430291518B4AAC24B54A00B0267 |   | null | 2020-10-15 15:24:10 | 192.168.31.49 | 1ms | Sucess

如题，StoreHost的ip地址是Console机器地址。这是个bug么

**Comment by xiangyang-gao** [comment]
Broker | NO. | Address | Version | Produce Massage TPS | Consumer Massage TPS | Yesterday Produce Count | Yesterday Consume Count | Today Produce Count | Today Consume Count | Operation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
dstable-broker-002 | 0(master) | 192.168.31.23:10911 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 104 | 0 | STATUS CONFIG
dstable-broker-002 | 1(slave) | 192.168.31.19:10915 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 0 | 32 | STATUS CONFIG
dstable-broker-001 | 0(master) | 192.168.31.19:10911 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 482 | 695 | STATUS CONFIG
dstable-broker-001 | 1(slave) | 192.168.31.23:10915 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 602 | 0 | STATUS CONFIG

**Comment by xiangyang-gao** [comment]
NameSvrAddrList
192.168.31.49:9876  192.168.31.26:9876

**Comment by vongosling** [comment]
You could check if it's the same machine. You can debug the code to determine the root cause of the problem by yourself.
