### ISSUE TITLE
rocketmq-flume-souce  packagename org.apache.rocketmq.flume.ng.souce is wrong!

### ISSUE THREAD

**Issue by yybmsrs** [apache/rocketmq-externals#64]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
rocketmq-flume-souce  packagename org.apache.rocketmq.flume.ng.souce is wrong!
- What did you do (The steps to reproduce)?
change org.apache.rocketmq.flume.ng.souce to org.apache.rocketmq.flume.ng.sou**r**ce
- What did you expect to see?

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by vongosling** [comment]
@shroman

**Comment by shroman** [comment]
@vongosling Fixed, but I don't have permissions
```
remote: Permission to apache/rocketmq-externals.git denied to shroman.
```
Same for the `apache/rocketmq`. Can you please fix permissions?

**Comment by vongosling** [comment]
I guess you could use an authenticator app to start double authentication. @zhouxinyu , Could you help to give @shroman some hint for this problem :-)

**Comment by vongosling** [comment]
ping @shroman @zhouxinyu

**Comment by shroman** [comment]
@zhouxinyu ok, thanks!
