### ISSUE TITLE
[rocketmq-console]There is a wrong display in OPS page

### ISSUE THREAD

**Issue by fantow** [apache/rocketmq-externals#641]
**BUG REPORT**

1. Please describe the issue you observed:
   **In my option,This is a wrong spell in the OPS page.**
![rocketMQ-extpng](https://user-images.githubusercontent.com/18530950/96564442-c0734780-12f5-11eb-9334-299728116e4a.png)

- What did you do (The steps to reproduce)?
   **I think there is a NameServer Address List,so the right abbreviation should be the "NameSrvAddrList".This can be consistent with the "NameSrv" component in the RocketMQ**

If this issue is nenecessary,may I create a PR to fix it?

**Comment by vongosling** [comment]
I am afraid I have to disagree with your suggestion here. Would you like to update it to NameServerAddressList, you could pr to fix it.

**Comment by fantow** [comment]
Thx,I have fixed it.
