### ISSUE TITLE
In rocketmq-console，the traceType of SubBefore's storeHost is null and the traceType of SubAfter's storeHost is also null

### ISSUE THREAD

**Issue by sunxi92** [apache/rocketmq-externals#649]
In rocketmq-console，the traceType of SubBefore's storeHost is null and the traceType of SubAfter's storeHost is also null.
I do the flowing tests:
(1) rocketmq 、rocketmq-console and consumer are deployed on the same machine, the traceType of Pub's information is normal.But the traceType of SubBefore's storeHost is null and the traceType of SubAfter's storeHost is also null.
(2)rocketmq and rocketmq-console are deployed on the virtual machine, consumer is deployed on the host machine, the traceType of Pub's information is normal.But the traceType of SubBefore's storeHost is null and the traceType of SubAfter's storeHost is also null.
Can someone help ?

**Comment by maixiaohai** [comment]
@sunxi92 This has been fixed at version 4.8.0. 
When client update to new version, you can have a try.
