### ISSUE TITLE
rocketmq-console not support rocketmq 4.7.1

### ISSUE THREAD

**Issue by wangjia2016** [apache/rocketmq-externals#650]
The issue tracker is **ONLY** used for bug report and feature request. 

Any question or RocketMQ proposal please use our [mailing lists](http://rocketmq.apache.org/about/contact/).

**BUG REPORT**

1. Please describe the issue you observed:
rocketmq-console not support rocket-mq 4.7.1

2. Please tell us about your environment:

rocketmq-4.7.1

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
![image](https://user-images.githubusercontent.com/16084076/99472768-45e52880-2984-11eb-96de-309f182f22e7.png)
![image](https://user-images.githubusercontent.com/16084076/99472783-4d0c3680-2984-11eb-8d60-e63c008835fa.png)
![image](https://user-images.githubusercontent.com/16084076/99472802-54cbdb00-2984-11eb-8a93-78cf6221897f.png)

**Comment by francisoliverlee** [comment]
very happy if u to make a PR fix it
