### ISSUE TITLE
rocketmq-console  build error

### ISSUE THREAD

**Issue by calvinGithub** [apache/rocketmq-externals#651]
**rocketmq-console编译错误，不符合code style，缺少空格**

1、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\config\RMQConfigure.java:85:34: error: '{' is not preceded with whitespace.
2、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\config\RMQConfigure.java:86:72: error: '||' is not preceded with whitespace.
3、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:239:11: error: 'if' is not followed by whitespace.
4、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:239:40: error: '{' is not preceded with whitespace.
5、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:245:10: error: 'else' is not preceded with whitespace.
6、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:245:10: error: '}' is not followed by whitespace.
7、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:245:14: error: 'else' is not followed by whitespace.
8、rocketmq-externals\rocketmq-console\src\main\java\org\apache\rocketmq\console\service\impl\TopicServiceImpl.java:245:14: error: '{' is not preceded with whitespace.

**Comment by vongosling** [comment]
You could build using the latest code.
