### ISSUE TITLE
rocketmq-cpp/producer/tryToCompressMessage没有判断msg是否被压缩过

### ISSUE THREAD

**Issue by kelly6** [apache/rocketmq-externals#66]
rocketmq-cpp/src/producer/DefaultMQProducer.cpp: tryToCompressMessage函数没有判断msg是否被压缩过，只判断了是否过大，如果压缩后发送失败进行重发并且body大小仍然>=getCompressMsgBodyOverHowmuch()， body会被压缩两次

**Comment by lizhanhui** [comment]
Good catch!

**Comment by vincentWangKB** [comment]
ok, I will fix it later, thanks your effort;

**Comment by lizhanhui** [comment]
@kelly6 You are using asynchronous send and try to re-send the message in the callback, right?

**Comment by kelly6** [comment]
@lizhanhui yes, sth like that.

**Comment by vongosling** [comment]
https://github.com/apache/rocketmq/pull/294 @vincentWangKB

**Comment by kelly6** [comment]
只修复了java客户端？ @vincentWangKB

**Comment by xpyzh** [comment]
不太理解这边在异步发送逻辑单独resetbody的原因，在大的try,catch,finally中不是已经resetbody，在异步发送的callback回调里再次使用改msg，应该不会是压缩后的吧

**Comment by shallowinggg** [comment]
> 看了下bugfix的代码[apache/rocketmq#294](https://github.com/apache/rocketmq/pull/294)，不太理解DefaultMQProducerImpl.sendKernelImpl在异步发送逻辑单独resetbody的原因，在大的try,catch,finally中不是已经resetbody，在异步发送的callback回调里再次使用改msg，应该不会是压缩后的吧

而且异步发送只会发送一次，不会出现重发的情况。

**Comment by ybonfire** [comment]
> 
> 
> 看了下bugfix的代码[apache/rocketmq#294](https://github.com/apache/rocketmq/pull/294)，不太理解DefaultMQProducerImpl.sendKernelImpl在异步发送逻辑单独resetbody的原因，在大的try,catch,finally中不是已经resetbody，在异步发送的callback回调里再次使用改msg，应该不会是压缩后的吧

是不是这段代码写错地方了。应该写在SYNC分支里？我感觉同步发送会产生重复压缩的问题

**Comment by lanqiuchenjian** [comment]
> 看了下bugfix的代码[apache/rocketmq#294](https://github.com/apache/rocketmq/pull/294)，不太理解DefaultMQProducerImpl.sendKernelImpl在异步发送逻辑单独resetbody的原因，在大的try,catch,finally中不是已经resetbody，在异步发送的callback回调里再次使用改msg，应该不会是压缩后的吧

看了代码，finally会重新赋初始值
