### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jordenLwq** [apache/rocketmq-externals#67]
The command '/bin/sh -c curl https://dist.apache.org/repos/dist/release/incubator/rocketmq/${ROCKETMQ_VERSION}/rocketmq-all-${ROCKETMQ_VERSION}-bin-release.zip -o rocketmq.zip           && unzip rocketmq.zip           && mv apache-rocketmq-all/* .           && rmdir apache-rocketmq-all            && rm rocketmq.zip' returned a non-zero code: 9
Unable to find image 'apache/incubator-rocketmq-namesrv:4.0.0-incubating' locally
Trying to pull repository docker.io/apache/incubator-rocketmq-namesrv ... 
Pulling repository docker.io/apache/incubator-rocketmq-namesrv
/usr/bin/docker-current: Error: image apache/incubator-rocketmq-namesrv:4.0.0-incubating not found.
See '/usr/bin/docker-current run --help'.
Unable to find image 'apache/incubator-rocketmq-broker:4.0.0-incubating' locally
Trying to pull repository docker.io/apache/incubator-rocketmq-broker ... 
Pulling repository docker.io/apache/incubator-rocketmq-broker
/usr/bin/docker-current: Error: image apache/incubator-rocketmq-broker:4.0.0-incubating not found.
See '/usr/bin/docker-current run --help'

**Comment by vongosling** [comment]
Please make clear your question.
