### ISSUE TITLE
The test are broken in console project

### ISSUE THREAD

**Issue by vongosling** [apache/rocketmq-externals#673]
In the console project, unit tests appear to be corrupted and need to be repaired. Is anyone willing to take this task? I'm willing to help you complete this optimization.

**Comment by zhangjidi2016** [comment]
I would like to add some unit tests for console project. Can I submit them in multiple PR?@vongosling

**Comment by vongosling** [comment]
Of course, you are welcome to engage in these tough tasks. First of all, I recommend not adding new unit tests, but fix some, delete some, and add more again. you could make one module or service test stable, and do the rest. At last, remember it, do not run the real cluster to test it, let it be more mocked using mockito.

**Comment by vongosling** [comment]
@zhangjidi2016  Any update?

**Comment by zhangjidi2016** [comment]
All controller interface tests of the Console project have been completed and submitted，please help to review them @vongosling @yuz10
