### ISSUE TITLE
How do I upgrade Flink？

### ISSUE THREAD

**Issue by wbigdata** [apache/rocketmq-externals#677]
![image](https://user-images.githubusercontent.com/31716799/107143013-9198e400-696d-11eb-9e3f-2c7f1c7c5723.png)

An exception occurred when I upgraded the Flink version to 1.11.2 in the POM file. In the org. Apache. Rocketmq. Flink. RocketMQSource class: ` always resolve a symbol curator `

I want to know how I can properly upgrade the Flink version. Thank you very much.

**Comment by vongosling** [comment]
Why do you want to upgrade? Flink does not seem to be compatible between 1.10.x and 1.11.2? You could check the Flink manual. I guess Flink seems to realize It's hard to solve the package conflict problem if not shade the core dependency in their all-in-one package.
