### ISSUE TITLE
[rocketmq-console]mvn package -DskipTests fail

### ISSUE THREAD

**Issue by mingjunChan** [apache/rocketmq-externals#684]
/code/extra/rocketmq-externals/rocketmq-console

mvn clean

mvn package -DskipTests
expect BUILD SUCCESS but BUILD FAILURE

**environment:**
 mvn -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/chenmingjun/sofeware/apache-maven-3.6.3
Java version: 1.8.0_231, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_231.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

chenmingjun@chenmingjundeMacBook-Pro rocketmq-console % ll
total 120
drwxr-xr-x  12 chenmingjun  staff    384  2 26 18:24 ./
drwxr-xr-x  36 chenmingjun  staff   1152  2 26 17:20 ../
-rw-r--r--   1 chenmingjun  staff     23  2 26 16:49 .gitignore
-rw-r--r--   1 chenmingjun  staff    322  2 26 16:49 .travis.yml
-rw-r--r--   1 chenmingjun  staff  29843  2 26 16:49 LICENSE
-rw-r--r--   1 chenmingjun  staff    176  2 26 16:49 NOTICE
-rw-r--r--   1 chenmingjun  staff   2312  2 26 16:49 README.md
drwxr-xr-x   3 chenmingjun  staff     96  2 26 16:49 doc/
-rw-r--r--@  1 chenmingjun  staff  10547  2 26 17:17 pom.xml
drwxr-xr-x   4 chenmingjun  staff    128  2 26 16:49 src/
drwxr-xr-x   5 chenmingjun  staff    160  2 26 16:49 style/
drwxr-xr-x   5 chenmingjun  staff    160  2 26 18:24 target/

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):
![image](https://user-images.githubusercontent.com/11487892/109290724-f2c42100-7862-11eb-84c4-d17536e8e824.png)
![image](https://user-images.githubusercontent.com/11487892/109290743-f9eb2f00-7862-11eb-88b5-18f26ca4241d.png)
![image](https://user-images.githubusercontent.com/11487892/109290768-ffe11000-7862-11eb-9552-784f71449fc7.png)
![image](https://user-images.githubusercontent.com/11487892/109290794-08394b00-7863-11eb-9861-027cb939704e.png)

**Comment by vongosling** [comment]
I could not find any error with your provided env. you should check your maven repository local cache. could you remove the project and re-clone and build it?

**Comment by mingjunChan** [comment]
I delete local repository maven-remote-resource-plugin-1.5.jar,and remove the project and re-clone and build it,but nothing change.
