### ISSUE TITLE
Why does the slave broker have produce count？

### ISSUE THREAD

**Issue by gengweifeng** [apache/rocketmq-externals#685]
Broker | NO. | Address | Version | Produce Massage TPS | Consumer Massage TPS | Yesterday Produce Count | Yesterday Consume Count | Today Produce Count | Today Consume Count | Operation
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
dstable-broker-002 | 0(master) | 192.168.31.23:10911 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 104 | 0 | STATUS CONFIG
dstable-broker-002 | 1(slave) | 192.168.31.19:10915 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 0 | 32 | STATUS CONFIG
dstable-broker-001 | 0(master) | 192.168.31.19:10911 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 482 | 695 | STATUS CONFIG
dstable-broker-001 | 1(slave) | 192.168.31.23:10915 | V4_7_1 | 0.00 | 0.00 | 0 | 0 | 602 | 0 | STATUS CONFIG

_Originally posted by @xiangyang-gao in https://github.com/apache/rocketmq-externals/issues/639#issuecomment-708999111_

What does the produce count mean？The slave broker can only be consumed, isn't it?

**Comment by maixiaohai** [comment]
@gengweifeng add more info will let community help you easily

**Comment by vongosling** [comment]
If no more details provided, you could check whether the master slave changed its role at some time.
