### ISSUE TITLE
阿里云版rocketmq-client和公版的区别

### ISSUE THREAD

**Issue by xianyongjie** [apache/rocketmq-externals#69]
为什么阿里云版本的rocketmq-client支持以下订阅方式而公版的不支持
consumer.subscribe("TopicTestMQ", "TagA||TagB", new MessageListener() { //订阅多个 Tag
            public Action consume(Message message, ConsumeContext context) {
                System.out.println("Receive: " + message);
                return Action.CommitMessage;
            }
        });
        //订阅另外一个 Topic
        consumer.subscribe("TopicTestMQ-Other", "*", new MessageListener() { //订阅全部 Tag
            public Action consume(Message message, ConsumeContext context) {
                System.out.println("Receive: " + message);
                return Action.CommitMessage;
            }
        });

**Comment by vongosling** [comment]
No different, this is not a correct place for your question.
