### ISSUE TITLE
[Replicator] The source task starts to check the position

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-externals#699]
**BUG REPORT**

1. Please describe the issue you observed:
![image](https://user-images.githubusercontent.com/30995057/112806918-e291a280-90a9-11eb-830a-11f734e108de.png)

- What did you do (The steps to reproduce)?
When the source task starts, check whether the position has been completed synchronously.
1. Filter out configs where brokerName and queueId do not exist.
2. Obtain the position twice at intervals, and compare whether the positions obtained twice before and after are consistent.
2.1 If they are consistent, the current position is considered to be the latest
2.2 If inconsistent, re-compare until timeout.

- What did you expect to see?
When the position synchronization is completed, that is, the current position is the latest position, and the task is started at this time.

- What did you see instead?
When the minOffset of the connector-position-topic is 0 and the amount of data is small, the data will be synchronized from the starting position. In this case, when the position has not yet been synchronized, the task is started, resulting in repeated data transmission.

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by odbozhou** [comment]
merged
