### ISSUE TITLE
maven中心库无法下载

### ISSUE THREAD

**Issue by coderElijah** [apache/rocketmq-externals#70]
<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>spring-boot-starter-rocketmq</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
maven加载不到

**Comment by lzysuqianqiu** [comment]
SNAPSHOT 快照版本肯定没有啊

**Comment by kmlkirito** [comment]
maven仓库中哪个版本都没有，jar要怎么下载？？？？？

**Comment by aiooly** [comment]
![_20180517095113](https://user-images.githubusercontent.com/6265479/40152460-dc09caa4-59b7-11e8-8e4a-0bd3bbbb6b54.png)
still not found the jar file.

**Comment by vongosling** [comment]
Yes, we didn't upload it to maven repository

**Comment by fangdong116** [comment]
why
