### ISSUE TITLE
[rocketmq-connect] Adjust the order of task state management.

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-externals#702]
**BUG REPORT**

1. Please describe the issue you observed:
The current task state management sequence:
**create new task** -> **check pending task** -> **check running task** -> **check stopping task** -> **check error/ stopped task**

When the current worker node goes online and rebalance occurs, it is recommended to close the task first to reduce the situation that the task runs in two instances at the same time.

- What did you do (The steps to reproduce)?
1.  Check the running tasks first.
2. If some tasks are closed, synchronize the position.

- What did you expect to see?
**check running task** -> **create new task** -> **check pending task** -> **check stopping task** -> **check error/ stopped task**

- What did you see instead?

2. Please tell us about your environment:

3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**Comment by odbozhou** [comment]
merged
