### ISSUE TITLE
[New Feature] A solution that supports any time delay message

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq-externals#709]
Now RocketMQ has weak support for delayed messages, and only supports 18 levels of delayed messages. We now have a solution that supports any time (second-level precision) delayed messages. Its architecture diagram is as follows:

![延时消息模块架构图【en】](https://user-images.githubusercontent.com/46882838/117393079-e96fc880-af25-11eb-8bee-55cd78e83e00.png)

**Implementation details**
- This feature is implemented as an extension.
- Consumers in different nodes belong to a common consumer group. Use Push mode to consume delayed messages in delayed topics. In this way, the load capacity of `delay expansion` can be horizontally expanded by increasing the number of delay group and the queues of delay Topic.
- In order to ensure the availability of the system, the function of automatic master selection is realized based on the Raft protocol. We intend to directly use this Dledger library(https://github.com/openmessaging/openmessaging-storage-dledger) that has implemented the Raft protocol.
- In order to ensure the consistency between the master and slave nodes, we take commitLog as the standard.

**Implementation process**
1. The producer sends a delay message to the delay Topic in the Broker.
2. The consumer located in the Master node in the`delay expansion` will consume the delayed messages from the delayed topic. After writing the message to commitLog, it will return `consume success`.
3. There will be another thread to save the message from commitLog to RocksDB.
4. A thread will read out the expiring messages from RocksDB in advance and add them to the time wheel.
5. Another thread will send the message to its original topic when the expiration time is reached. And write the delivered timestamp and message into commitLog to ensure that another slave node knows which message will be delivered from when it becomes the master node.

**We want to know whether this solution is ok. If it meets the requirements, we will implement it according to the above architecture diagram**

**Comment by vongosling** [comment]
Since we have a wip pr for this feature. you could call for discussion in this thread, https://github.com/apache/rocketmq/pull/2290.

**Comment by cserwen** [comment]
> Since we have a wip pr for this feature. you could call for discussion in this thread, [apache/rocketmq#2290](https://github.com/apache/rocketmq/pull/2290).

We want to implement this feature in the form of external components, so an issue was created under this repo. Okay, let's discuss it in that issue.

**Comment by vongosling** [comment]
Thanks for your explanation. We are preparing for the newer dynamic modules to support. You could discuss this in the provided links. I think this new pluggable mechanism could be designed very quickly, and since there are a few waves of people interested in this feature, I'd like to have a default implementation in the main repository.

**Comment by maixiaohai** [comment]
> Thanks for your explanation. We are preparing for the newer dynamic modules to support. You could discuss this in the provided links. I think this new pluggable mechanism could be designed very quickly, and since there are a few waves of people interested in this feature, I'd like to have a default implementation in the main repository.

Hi @vongosling，We have strong demand for flexible and wide range time delay messages in financial cases. 
Can you share the new pluggable mechanism design? We want to implement refer to the community and when community part is ready, we could migrate to it quickly and smoothly.
