### ISSUE TITLE
Any progress about the RocketMQ-JMS Project?

### ISSUE THREAD

**Issue by yunze-wang** [apache/rocketmq-externals#738]
I found the last  commit is at 2019,according to the pom,it only support jms1.1,but according to the official documentation http://rocketmq.apache.org/docs/roadmap/,it support jms2.0.

THX

**Comment by vongosling** [comment]
You are correct. No new needs drive to adapt 2.0. Would you like to contribute here, what are your needs here? 1.1 is sufficient in most cases AFAIK.

**Comment by yunze-wang** [comment]
Hi vongosling,
  I'm trying to use this client,I've packaged this project using 'MVN',and deployed to our ESB,but our ESB can't load this driver,it can hanlde RabbitMq JMS client or ActiveMq JMS client very well using JMS Adapter,would you provide an release version of JMS client jar file just like the RocketMq Client.
BR.

**Comment by vongosling** [comment]
I'm afraid this is not the case(you could deploy in your local repos). Our core committer is not working on this. Would you like to join in and become the maintainer of this project? @duhenglucky

**Comment by vongosling** [comment]
No response for a long time, I will close it. any thoughts welcome to put :-)
