### ISSUE TITLE
为4.2.0添加docker支持

### ISSUE THREAD

**Issue by airclear** [apache/rocketmq-externals#74]
**FEATURE REQUEST**

1. 为4.2.0添加docker支持

**Comment by vongosling** [comment]
Would you update your issue description just following our template? the same issue in your PR

**Comment by airclear** [comment]
I'm sorry, but I didn't check it carefully.
I find that， when I use openjdk8 to run the broker , it crashed. switch to oraclejdk8 , it works good.
I can't resolve this issues right now， so I gona close this PR first
