### ISSUE TITLE
[RocketMQ Console] Add RocketMQ message trace timeline Graph UI

### ISSUE THREAD

**Issue by StyleTang** [apache/rocketmq-externals#743]
Add RocketMQ message trace timeline Graph UI.

For now, the RocketMQ console only displays the message trace view data list but not a graph, it is hard for user to understand what the data means. In order to make it easier for users to use message trace, we use echarts to draw the timeline chart.

- [ ] Frontend
	- [ ] Implement message trace graph UI
	  - [ ] Produce message trace node
	  - [ ] Consume message trace node
	    - [ ] message retry trace node support 
	    - [ ] Multiple subscription groups support
	- [ ] Upgrade echarts version to support UI
- [ ] Backend 
	- [ ] Add viewMessageTraceGraph method (aggregate MessageTraceView list)
	- [ ] MessageTraceView add filed requestId and retryTimes
	- [ ] Add Unit Test for this change

Feel free to comment it if you have any suggestions. 😀

**Comment by vongosling** [comment]
@StyleTang will you update the checkbox if any module is finished? I would like to follow up this pr :-)
