### ISSUE TITLE
rocketmq-flink- the checkPointLock should use the context checkpointLock，No need to define separately and should not

### ISSUE THREAD

**Issue by chenliuyang1989** [apache/rocketmq-externals#748]
First：
For the message get from Rocketmq，
we should use the context checkpoint  to insure the checkpointing and the emission of elements must never occur at the same time。
If we use a seperate lock，it will not work。
![image](https://user-images.githubusercontent.com/4150132/126133890-21ec07ee-1cbb-48c8-8004-f55737b5f4f6.png)

Second,we should keep the Atomic operation for the operation of emission of elements  and the operation of update the
offset of rocketmq topic.

![image](https://user-images.githubusercontent.com/4150132/126134059-26128eb6-b033-40bc-b8eb-182e58895fbb.png)

**Comment by chenliuyang1989** [comment]
should not define a seperate lock。
![image](https://user-images.githubusercontent.com/4150132/126134253-4557e0df-f6f1-4c45-ac66-c3088eaa51d6.png)

**Comment by vongosling** [comment]
@duhenglucky

**Comment by chenliuyang1989** [comment]
any updates？
