### ISSUE TITLE
Uncaught SyntaxError: Unexpected token z in JSON at position 0

### ISSUE THREAD

**Issue by Matrixgo** [apache/rocketmq-externals#749]
【背景】
部署：git clone到本地，编译打包，直接java -jar部署到centos服务器

现象：大概一月前部署后一切正常，最近发现访问控制台无法进入，前端有报异常

排查：
		>日志：无相关报错
		>重启控制台：未解决
		>重启NameServer：未解决
		>重启Broker：未解决
		>单元测试生产者和消费者能力正常：能力正常，控制台未解决
		>重新本地源码编译控制台打包后部署：未解决
		>更换控制台版本源码编译打包后部署：未解决

期望：如果是BUG希望能尽快解决，如果是使用问题烦请指正

报错信息：
![2333](https://user-images.githubusercontent.com/41765932/126292499-f2faa7bd-fde8-4b24-9e21-c5e5047dd140.png)

Debug：
![233333](https://user-images.githubusercontent.com/41765932/126293296-9c3d0501-05df-44d5-946d-faaba26afc3d.png)

**Comment by chengshanbin** [comment]
用的是最新的版本吗？

**Comment by francisoliverlee** [comment]
you can try a demo on [ https://start.aliyun.com/course?spm=a2ck6.17690074.0.0.322c2e7dWBiGaU&id=ASeJlmpX]( https://start.aliyun.com/course?spm=a2ck6.17690074.0.0.322c2e7dWBiGaU&id=ASeJlmpX)

![image](https://user-images.githubusercontent.com/5908412/126369572-400ed6d9-e14c-4d93-9ca5-b74296f08f72.png)

**Comment by Matrixgo** [comment]
> 用的是最新的版本吗？

是的

**Comment by Matrixgo** [comment]
> you can try a demo on [ https://start.aliyun.com/course?spm=a2ck6.17690074.0.0.322c2e7dWBiGaU&id=ASeJlmpX](https://start.aliyun.com/course?spm=a2ck6.17690074.0.0.322c2e7dWBiGaU&id=ASeJlmpX) , that could help know where is not right
> 
> ![image](https://user-images.githubusercontent.com/5908412/126369572-400ed6d9-e14c-4d93-9ca5-b74296f08f72.png)

好的 我去学习下 谢谢

**Comment by Matrixgo** [comment]
@vongosling @francisoliverlee @chengshanbin 
现在（202107211035）尝试访问又能正常进入控制台了，从发起这个issue到现在中间没有改动和重新部署过。

依然断点昨天前端angular.js解析JSON的位置，发现初始传值不同且加了转移符，如下图。是否可能是前端依赖的包动态更新过？
![jinx2333](https://user-images.githubusercontent.com/41765932/126422105-f30349cc-ea02-45e2-9c69-42746b7e1ecd.png)
