### ISSUE TITLE
rocketmq-console：It does not work when setting server.servlet.context-path in application.properties

### ISSUE THREAD

**Issue by yiminyangguang520** [apache/rocketmq-externals#750]
**1、It does not work when setting server.servlet.context-path in application.properties**

- What did you do (The steps to reproduce)?
   1、build rocketmq-console docker image with master branch and rocketmq-externals/rocketmq-console/src/main/docker/Dockerfile
   2、add server.servlet.context-path property in application.properties and enable login 

- What did you expect to see?
   rocketmq-console can work well

- What did you see instead?
   rocketmq-console can not work well，the page occur error，it can not get ops information

2. Please tell us about your environment:
    os: centos 7
    docker version: 20.10.7

**Comment by StyleTang** [comment]
@yiminyangguang520 
Could you fork apache/rocketmq-externals and then push your changes to your own repository, I will help you troubleshooting.

**Comment by yiminyangguang520** [comment]
@StyleTang 
I have forked apache/rocketmq-externals and pushed my changes to https://github.com/yiminyangguang520/rocketmq-externals，please help me，thank you！

**Comment by StyleTang** [comment]
@yiminyangguang520 
Thanks for reporting this issue, my PR will fix it (pending for review ).
If you want to fix your issue immediately, you can just cherry-pick the commit.

**Comment by yiminyangguang520** [comment]
@StyleTang thank you for your replay, best wishes to you!
