### ISSUE TITLE
[rocketmq-console] message trace compatibility

### ISSUE THREAD

**Issue by StyleTang** [apache/rocketmq-externals#768]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
Test different versions of RocketMQ Client to make RocketMQ console message trace compatible with older versions
2. Provide any additional detail on your proposed use case for this feature.
Test edge case happen in different RocketMQ client version, and make it compatible.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
should-have

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:
NO

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

This is a compatibility testing request for message trace functionality across different RocketMQ client versions in rocketmq-console.

**Feasibility:** Feasible but requires systematic cross-version testing.
**Scope:** rocketmq-console message trace parsing/display; compatibility with old and new client versions.
**Compatibility:** The key concern — ensuring the console can correctly parse trace data from clients using different trace formats.

This is a valid concern. Message trace format has evolved across RocketMQ versions, and the console should handle backward compatibility gracefully. A matrix of client versions × trace format variants would be useful.

---
*Automated evaluation by RockteMQ-AI*
