### ISSUE TITLE
Facing ussue when using flink version 1.1.2

### ISSUE THREAD

**Issue by yonghaozhang** [apache/rocketmq-externals#775]
Hi guys,
I am using flink version 1.1.2, which is lower than master version 1.1.3. So I face NoclassFoundError. Is some milestone support flink 1.1.2 ?

thanks a lot

**Comment by SteNicholas** [comment]
> Hi guys,
> I am using flink version 1.1.2, which is lower than master version 1.1.3. So I face NoclassFoundError. Is some milestone support flink 1.1.2 ?
> 
> thanks a lot

@yonghaozhang , you could update the version of the Flink maven dependencies. The RocketMQ legacy source and sink could be used in Flink 1.12.
