### ISSUE TITLE
run rocketmq-broker using docker  EXIT(137)

### ISSUE THREAD

**Issue by zhiqunz** [apache/rocketmq-externals#78]
**BUG REPORT**

when I try to build and run  name server and broker on MAC,
using the following sh:
```
rocketmq-externals/rocketmq-docker/4.1.0-incubating/play.sh
```

name server is ok, but broker container was automatically KILLED and exit(137)

Anyway, I tried to start the broker in name server container.

The broker was automatically killed. Is there any suggestion?

error message:
```
root@46dca5673f74:/opt/rocketmq-4.1.0-incubating# sh bin/mqbroker -n localhost:9876 &
[1] 35
root@46dca5673f74:/opt/rocketmq-4.1.0-incubating# Killed

[1]+  Exit 137                sh bin/mqbroker -n localhost:9876

```

**Comment by k19810703** [comment]
I have the same problem.

**Comment by ququzone** [comment]
also same problem

**Comment by huanwei** [comment]
@k19810703 @ququzone As I mentioned in my PR, I believe the issue you encountered was due to the default setting of broker's JVM is much more higher than your node's memory resource capacity. To avoid this you need to adjust your parameters according. For example:

```
JAVA_OPT="${JAVA_OPT} -server -Xms256m -Xmx256m -Xmn128m"
```

**Comment by vongosling** [comment]
@zhiqunz Could you check our community latest contribution, any problem, welcome to send email to our user email list
