### ISSUE TITLE
[Rocketmq-flink] Rocketmq client does not guaranteed to be closed properly.

### ISSUE THREAD

**Issue by ni-ze** [apache/rocketmq-externals#788]
![image](https://user-images.githubusercontent.com/31175234/129850264-19ea2fd6-f628-4b3e-9039-2505f4431c4e.png)
DefaultMQPullConsumer.start() in open method, and pull message in run method.

DefaultMQPullConsumer.start() would create netty client and many other resources, It should guaranteed to be closed properly under any conditions.

It is recommended to use as follows
```java
DefaultMQPullConsumer consumer =null;
try{
//initializate
...

//start
consumer.start()

//use
...


} finally {
     if (consumer != null){
       consumer.shutdown();
  }
}

```

**Comment by SteNicholas** [comment]
@ni-ze , `RocketMQSourceFunction` starts the `DefaultMQPullConsumer` in the `open()` method and closes the `DefaultMQPullConsumer` in the `close` method. This behavior could guarantee the `DefaultMQPullConsumer` to be closable.
