### ISSUE TITLE
why Multi-producer instance use the same instanceName?

### ISSUE THREAD

**Issue by 505703441** [apache/rocketmq-externals#789]
#704 

rocketmq-client:4.8.0
org.apache.rocketmq.client.impl.MQClientManager.getOrCreateMQClientInstance()
same instanceName use same instance->the same TCPLink

**Comment by odbozhou** [comment]
1、If you have any questions about pr 704, you can check the issue https://github.com/apache/rocketmq-externals/issues/696
2、It is not necessary to use multiple instance names for the same client instance

**Comment by odbozhou** [comment]
If you still have questions, please reopen this issue
