### ISSUE TITLE
[rocketmq-iot-bridge] Support to query the info of connected clients via HTTP

### ISSUE THREAD

**Issue by cserwen** [apache/rocketmq-externals#811]
**FEATURE REQUEST**

1. Please describe the feature you are requesting.
In our company, there are a lot of devices which use this project, but we can't view the number of client nodes connected to the service and can't know the load pressure of the service. So We want to provide a web url to query it because HTTP is easy to use for anyone in anywhere. For example:
![image](https://user-images.githubusercontent.com/46882838/132179571-51496d84-0cf4-44f3-877d-8cf06d9e1bf3.png)

2. Provide any additional detail on your proposed use case for this feature.
We can achieve this function by adding a lite HTTP server.

3. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?
must-have
4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

**Comment by odbozhou** [comment]
merged
