### ISSUE TITLE
sink哪里用到的了负载均衡

### ISSUE THREAD

**Issue by 505703441** [apache/rocketmq-externals#815]
![image](https://user-images.githubusercontent.com/39154875/134463699-5ba6fa0d-dbd5-43c0-b2d3-b99cadf65c30.png)
我看这个WorkerSinkTask.java只用到了fetchSubscribeMessageQueues，其它地方也没有看到fetchMessageQueuesInBalance，这个是怎么用做的负载均衡？

**Comment by odbozhou** [comment]
Load balancing is achieved through runtime
