### ISSUE TITLE
[rocketmq-flink] convertToRowTypeInfo() should return field name

### ISSUE THREAD

**Issue by liyubin117** [apache/rocketmq-externals#816]
`RocketMQDynamicTableSink#convertToRowTypeInfo()`
now just return field type information, so we don`t have the neccessary information to serialize field name to body, or use real field name instead of f0/f1.. relying on the field order to identify the key column

**Comment by liyubin117** [comment]
I have enhanced the function in our department, if it`s neccessary, I will create a merge request

**Comment by duhenglucky** [comment]
@liyubin117 rocketmq-flink  has been moved to this [repo](https://github.com/apache/rocketmq-flink), welcome to submit an issue and PR
