### ISSUE TITLE
[rocketmq-connect] Autocreate subscription group

### ISSUE THREAD

**Issue by Git-Yang** [apache/rocketmq-externals#821]
1. Please describe the issue you observed:
-  You need to create a subscription group manually, when the cluster disables the function of automatically creating a subscription group.
- The creation of subscription groups floods, maintaining too many useless subscription groups.
- To re-create the subscription group when the service restarts, the full amount of historical data needs to be loaded.

2. What did you do (The steps to reproduce)?
- Subscription group is automatically created, when the cluster turns off the function of automatically creating a subscription group.
- DefaultMQAdmin uses the default subscription group and generates a unique InstanceName in order to avoid client conflicts.
- DefaultMQPullConsumer is the same as DefaultMQAdmin.
- The DefaultMQPushConsumer subscription group rule is the default prefix + unique workId.

**Comment by RockteMQ-AI** [comment]
**Issue Evaluation**

Category: `enhancement` | Status: **Evaluated**

**Feasibility:** Feasible
**Scope:** rocketmq-connect runtime

This is a valid enhancement request for the rocketmq-connect runtime. When `autoCreateSubscriptionGroup` is disabled on the broker, users must manually create subscription groups — which is operationally burdensome. The proposal to have the connect runtime auto-create subscription groups (with proper naming and cleanup) is reasonable.

**Key considerations:**
- Subscription group naming should follow a predictable convention (e.g., `connect-{connectorName}-{taskId}`)
- Cleanup logic is needed to avoid subscription group proliferation
- Idempotent creation to handle restarts without loading full historical data

**Note:** Filed September 2021. Please verify if this has been addressed in recent rocketmq-connect releases.

---
*Automated evaluation by RockteMQ-AI*
