### ISSUE TITLE
rocketmq-cpp when compiled with msvc, "there is no stdbool.h", and with visual studio 2010, not support c++11 

### ISSUE THREAD

**Issue by nirenxiaoxiao** [apache/rocketmq-externals#85]
The issue tracker is **ONLY** used for bug report and feature request. 

**BUG REPORT**

1. Please describe the issue you observed:

- Use cmake produce the sln file, open sln with visual studio 2010 to build the project

- Wish to get the static lib rocketmq.lib

- What did you see instead?
  See some errors, no stdbool.h, thread, etc

2. Please tell us about your environment:
Windows 7 64bit, Visual studio 2010
3. Other information (e.g. detailed explanation, logs, related issues, suggestions how to fix, etc):

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

2. Provide any additional detail on your proposed use case for this feature.

2. Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have). Are you currently using any workarounds to address this issue?

4. If there are some sub-tasks using -[] for each subtask and create a corresponding issue to map to the sub task:

- [sub-task1-issue-number](example_sub_issue1_link_here): sub-task1 description here, 
- [sub-task2-issue-number](example_sub_issue2_link_here): sub-task2 description here,
- ...

**Comment by vongosling** [comment]
ping @ShannonDing @wlliqipeng

**Comment by vongosling** [comment]
@nirenxiaoxiao please see my previous feedback
