### ISSUE TITLE
[RIP-40] Apache Rocketmq Playbook

### ISSUE THREAD

**Issue by lwclover** [apache/rocketmq-externals#880]
Apache Rocketmq Playbook可以部署一个完整Apache Rocketmq集群（包括Apache Rocketmq Exporter）。

Apache Rocketmq Playbook具有幂等性，重复执行时不会重启正在运行的进程，所以可以进行Apache Rocketmq集群的在线扩容。

Apache Rocketmq集群缩容涉及到数据的收缩，一般不考虑在Apache Rocketmq Playbook上支持缩容。

Apache Rocketmq Playbook集成了部署环境初始化、可运行包下载、os参数调优、broker最佳配置、Rocketmq集群部署、Exporter部署、添加开机自启动机制等任务编排到一起，实现了大规模集群自动化部署。

<img width="625" alt="cicd" src="https://user-images.githubusercontent.com/4252409/161951911-1626aba7-5ec6-42c1-a81d-0b133e00279a.png">

**Comment by duhenglucky** [comment]
merged
