### ISSUE TITLE
Why not find rocketmq-console?

### ISSUE THREAD

**Issue by coder-PengWenHao** [apache/rocketmq-externals#900]
rocketmq-console

**Comment by xbronze** [comment]
I guess you are in the master branch, please switch to the develop branch.

**Comment by xbronze** [comment]
> rocketmq-console

I guess you are in the master branch, please switch to the dev branch

**Comment by caigy** [comment]
`rocketmq-console` has been graduated and renamed as `rocketmq-dashboard` with new repository: https://github.com/apache/rocketmq-dashboard

**Comment by howhich** [comment]
damn,thx alot bro!
