### ISSUE TITLE
Could not find spring-boot-starter-rocketmq

### ISSUE THREAD

**Issue by maskleo** [apache/rocketmq-externals#93]
```xml
<dependency>
    <groupId>org.apache.rocketmq</groupId>
    <artifactId>spring-boot-starter-rocketmq</artifactId>
    <version>1.0.0-SNAPSHOT</version>
</dependency>
```

Failed to execute goal on project rocketmq-server: Could not resolve dependencies for project edu.maskleo:rocketmq-server:jar:0.0.1-SNAPSHOT: Could not find artifact org.apache.rocketmq:spring-boot-starter-rocketmq:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by vongosling** [comment]
we could not push the jar to maven repository, you need to mvn install locally

**Comment by maskleo** [comment]
@vongosling  Thanks.
