### ISSUE TITLE
RocketMQ + Spark Structured Streaming Integration can not work well

### ISSUE THREAD

**Issue by hengyuan** [apache/rocketmq-externals#94]
1.RocketMQ + Spark Structured Streaming Integration Guide
2.It is not good to run according to guidance
val spark = SparkSession
      .builder
      .master("local[2]")
      .appName("StructuredNetworkWordCount")
      .getOrCreate()
    val df = spark
      .readStream
      .format("org.apache.spark.sql.rocketmq.RocketMQSourceProvider")
      .option("nameServer", "192.168.2.210:9876;192.168.2.211:9876")
      .option("topic", "testtopic")
      .option("groupId","streaming1")
      .load()
    df.printSchema()
    df.selectExpr("CAST(body AS STRING)").groupBy("body").count()
    val query = df.writeStream
      .outputMode("update")
      .format("console")
      .start()
    query.awaitTermination()
3.how to set groupId for rocketMq for identifying the consumer

**Comment by fuyufjh** [comment]
1. Sorry for the mistake. The document is for RocketMQ, I'll make an PR to remove those Kafka words
2. Do not set `groupId` manually. The consumer will generate one for you automatically.

**Comment by hengyuan** [comment]
1.other more,in the guide,**Creating a RocketMQ Source for Streaming Queries** and **Creating a RocketMQ Source for Batch Queries**  are same?why?
2.when streaming running,only one job.I did not see batch by batch running.please Fully tested and perfect guide.
3.we use groupId to Control data auth.if you generate one for us automatically,it will be bad.
very thanks!

**Comment by fuyufjh** [comment]
1. `spark.readStream()` for streaming source, while `spark.read()` for batch source.
2. Please make sure there is new messages coming in. You may take [RocketMQDataSourceTest.java](https://github.com/apache/rocketmq-externals/blob/master/rocketmq-spark/src/test/java/org/apache/rocketmq/spark/sql/RocketMQDataSourceTest.java) as an example, which contains an internal mocked RocketMQ deployment.
3. `groupId` may sometimes be misconfigured by user, and cause unexpected behavior, so in this first version I disallowed this option. Anyway, further discussion is welcomed for your case.

**Comment by hengyuan** [comment]
Thank you for your patience!!!
I am especially looking forward to customizing the groupId.use groupId,we can do checkpoint.so that application can continue work from the checkpoint offset.Ensure that data is not lost when the application  
crashed

**Comment by fuyufjh** [comment]
@hengyuan Here checkpoint is supported on spark side. The RocketMQ data source stores **committed** offsets in spark's `checkpointLocation`, which is typically on HDFS or other reliable storage.

Relies on RocketMQ's offset storage is a bad idea. For example, once your cluster crashed some data may be still in process (aka. not committed to Sink), however, RocketMQ considers them as “already consumed”, so this segment of data would be lost.
